In [2]:
import pandas as pd

/home/user/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
import warnings as warn

In [4]:
warn.filterwarnings('ignore')

In [27]:
import pandas as pd
import numpy as np

In [31]:
np.empty(3)

array([4.2931542e-315, 0.0000000e+000, 1.5810101e-322])

In [30]:
list(range(5))

[0, 1, 2, 3, 4]

In [7]:
list(range(5))

[0, 1, 2, 3, 4]

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
list(np.arange(1.5, 2.5, 0.3))

[1.5, 1.8, 2.1, 2.4000000000000004]

In [12]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
# list(range(0.4,10.4))

In [11]:
list(np.arange(.4 , 10.4 , 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.200000000000003]

In [15]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [169]:
np.linspace(1,4,3)

array([1. , 2.5, 4. ])

In [170]:
np.arange(1,4,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8])

In [173]:
np.logspace(1,4,10)

array([   10.        ,    21.5443469 ,    46.41588834,   100.        ,
         215.443469  ,   464.15888336,  1000.        ,  2154.43469003,
        4641.58883361, 10000.        ])

In [172]:
np.arange(2,3,0.2)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [160]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [161]:
np.logspace(1,5,5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [162]:
np.linspace(1,5 , 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [167]:
np.logspace(1,5,15,base = 2)

array([ 2.        ,  2.43802731,  2.97198858,  3.62289466,  4.41635805,
        5.38360077,  6.56268285,  8.        ,  9.75210923, 11.88795431,
       14.49157863, 17.66543222, 21.53440308, 26.25073139, 32.        ])

In [164]:
np.logspace(1,5 , 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [174]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [175]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [176]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [165]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros((4,3,2,1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]])

In [26]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [27]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [18]:
np.random.rand(3,3)

array([[0.8669848 , 0.79732641, 0.24453088],
       [0.84820734, 0.76803668, 0.63957593],
       [0.51939093, 0.66662963, 0.32859855]])

In [177]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [178]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [179]:
np.empty((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones(1)

array([1.])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
arr = np.ones((3,4))

In [32]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((4,3,2,1))

array([[[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]]])

In [34]:
arr = np.ones((4,4))

In [182]:
arr+2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [183]:
arr*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [184]:
arr**3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [185]:
arr/3

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [35]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [37]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [38]:
arr**2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
arr -1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [41]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [42]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.ones((2,3)) == np.empty((2,3))

array([[ True,  True,  True],
       [ True,  True,  True]])

In [181]:
arr = np.ones((3,3))

In [45]:
arr1 = np.eye(2)

In [46]:
arr1

array([[1., 0.],
       [0., 1.]])

In [47]:
arr1 = np.eye(5)

In [48]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.eye(1)

array([[1.]])

In [51]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [186]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [190]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [191]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
pd.DataFrame(np.eye(3))

     0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [53]:
pd.DataFrame(arr1)

     0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [195]:
pd.DataFrame(np.eye(7))

     0    1    2    3    4    5    6
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [19]:
np.random.rand(2,3)

array([[0.25904487, 0.14466925, 0.48096832],
       [0.23285716, 0.05817793, 0.87208496]])

In [55]:
np.random.rand(2)

array([0.76882147, 0.38099256])

In [21]:
np.random.randn(3,3)

array([[ 1.2715022 ,  0.03781501, -0.47102375],
       [-0.252335  ,  1.14460315,  0.0566313 ],
       [-0.9942498 ,  2.07265885, -1.45942501]])

In [57]:
np.random.randn(1,2)

array([[1.58797678, 0.8813734 ]])

In [24]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [58]:
np.random.randn(5)

array([0.10185527, 0.86295634, 1.25934204, 0.6044966 , 0.90812202])

In [59]:
np.random.randn(2,3)

array([[ 0.49717502,  0.70744463,  0.17055768],
       [-0.90541612, -1.01242424,  0.85640473]])

In [60]:
np.random.randint(1,5,(1))

array([4])

In [61]:
np.random.randint(1,10,(3,3))

array([[1, 5, 9],
       [8, 1, 9],
       [2, 1, 8]])

In [62]:
arr2 = np.random.randint(1,5 , (3,4))

In [63]:
np.random.randint(1,5,(2,2))

array([[3, 3],
       [3, 3]])

In [64]:
arr = np.random.randint(1,5,(3,4))

In [198]:
np.random.randn(3,3)

array([[ 0.41900934, -0.1803621 , -0.59333372],
       [ 0.97183984, -1.01723286,  1.8113218 ],
       [ 1.97675625, -1.78686782, -1.62343804]])

In [199]:
np.random.randn(7)

array([-2.00385332, -0.52893862,  2.22261105,  0.20696549, -0.39873017,
       -0.00637449, -1.72239735])

In [197]:
np.random.randn(2)

array([0.62902415, 0.17381202])

In [201]:
np.random.randint(100)

88

In [209]:
np.random.randint(1,10,(4,4))

array([[7, 5, 8, 9],
       [9, 1, 9, 5],
       [4, 9, 4, 5],
       [5, 9, 7, 6]])

In [210]:
np.random.randint(10)

5

In [211]:
arr2.size

16

In [212]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [213]:
arr.shape

(3, 3)

In [217]:
np.random.randint(1,10,7)

array([5, 4, 6, 3, 2, 4, 5])

In [218]:
np.random.randint(1,10,7)

array([8, 1, 7, 9, 9, 1, 2])

In [68]:
arr.size

12

In [69]:
arr2.shape

(3, 4)

In [70]:
arr.reshape(2,6)

array([[1, 4, 1, 3, 3, 3],
       [1, 4, 2, 1, 1, 3]])

In [71]:
arr.reshape(1,12)

array([[1, 4, 1, 3, 3, 3, 1, 4, 2, 1, 1, 3]])

In [72]:
arr2.reshape(6,2)

array([[2, 1],
       [4, 3],
       [4, 3],
       [4, 3],
       [3, 2],
       [1, 3]])

In [73]:
arr2.reshape(2,6)

array([[2, 1, 4, 3, 4, 3],
       [4, 3, 3, 2, 1, 3]])

In [74]:
arr2.reshape(4,3)

array([[2, 1, 4],
       [3, 4, 3],
       [4, 3, 3],
       [2, 1, 3]])

In [219]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [220]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
arr.reshape(4,-2)

array([[1, 4, 1],
       [3, 3, 3],
       [1, 4, 2],
       [1, 1, 3]])

In [221]:
arr.reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [225]:
arr = np.random.randint(1,10,(4,4))

In [229]:
arr.reshape(2,8,1)

array([[[8],
        [6],
        [4],
        [4],
        [5],
        [1],
        [1],
        [9]],

       [[3],
        [2],
        [9],
        [5],
        [5],
        [4],
        [5],
        [6]]])

In [230]:
arr

array([[8, 6, 4, 4],
       [5, 1, 1, 9],
       [3, 2, 9, 5],
       [5, 4, 5, 6]])

In [233]:
arr.reshape(4,-2)

array([[8, 6, 4, 4],
       [5, 1, 1, 9],
       [3, 2, 9, 5],
       [5, 4, 5, 6]])

In [78]:
arr2.reshape(4,-1)

array([[2, 1, 4],
       [3, 4, 3],
       [4, 3, 3],
       [2, 1, 3]])

In [79]:
arr2.reshape(4,-1432453453)

array([[2, 1, 4],
       [3, 4, 3],
       [4, 3, 3],
       [2, 1, 3]])

In [80]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[2]]],


         [[[1]]],


         [[[4]]]],



        [[[[3]]],


         [[[4]]],


         [[[3]]]]],




       [[[[[4]]],


         [[[3]]],


         [[[3]]]],



        [[[[2]]],


         [[[1]]],


         [[[3]]]]]])

In [81]:
arr1 = np.random.randint(1,10 , (5,6))

In [82]:
arr1

array([[8, 5, 5, 8, 2, 7],
       [9, 7, 3, 2, 7, 9],
       [2, 5, 8, 2, 1, 5],
       [1, 4, 7, 1, 7, 4],
       [8, 9, 9, 4, 8, 8]])

In [83]:
arr

array([[1, 4, 1, 3],
       [3, 3, 1, 4],
       [2, 1, 1, 3]])

In [84]:
arr>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [85]:
arr1 >8

array([[False, False, False, False, False, False],
       [ True, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True, False, False, False]])

In [86]:
arr<4

array([[ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [87]:
arr<=4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
arr>=4

array([[False,  True, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [89]:
arr

array([[1, 4, 1, 3],
       [3, 3, 1, 4],
       [2, 1, 1, 3]])

In [90]:
arr[arr>3]

array([4, 4])

In [91]:
arr1

array([[8, 5, 5, 8, 2, 7],
       [9, 7, 3, 2, 7, 9],
       [2, 5, 8, 2, 1, 5],
       [1, 4, 7, 1, 7, 4],
       [8, 9, 9, 4, 8, 8]])

In [92]:
arr

array([[1, 4, 1, 3],
       [3, 3, 1, 4],
       [2, 1, 1, 3]])

In [234]:
arr

array([[8, 6, 4, 4],
       [5, 1, 1, 9],
       [3, 2, 9, 5],
       [5, 4, 5, 6]])

In [235]:
arr<5

array([[False, False,  True,  True],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [False,  True, False, False]])

In [236]:
arr>5

array([[ True,  True, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False,  True]])

In [237]:
arr==5

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

In [238]:
arr

array([[8, 6, 4, 4],
       [5, 1, 1, 9],
       [3, 2, 9, 5],
       [5, 4, 5, 6]])

In [240]:
arr[0,[1,2,3]]

array([6, 4, 4])

In [243]:
arr[0:4,[0,1,2,3]]

array([[8, 6, 4, 4],
       [5, 1, 1, 9],
       [3, 2, 9, 5],
       [5, 4, 5, 6]])

In [93]:
arr[0,[1,2,3]]

array([4, 1, 3])

In [94]:
arr1[0,[0,1]]

array([8, 5])

In [95]:
arr[0:2,[0,1]]

array([[1, 4],
       [3, 3]])

In [96]:
arr

array([[1, 4, 1, 3],
       [3, 3, 1, 4],
       [2, 1, 1, 3]])

In [97]:
arr[0:3,[0,1,2,3]]

array([[1, 4, 1, 3],
       [3, 3, 1, 4],
       [2, 1, 1, 3]])

In [168]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [98]:
arr1[arr1 >8]

array([9, 9, 9, 9])

In [99]:
arr1[arr1 >8]

array([9, 9, 9, 9])

In [100]:
arr1[2:4 , [2,3]]

array([[8, 2],
       [7, 1]])

In [101]:
arr[(1<arr) & (arr <3)]

array([2])

In [244]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [245]:
arr1 = np.random.randint(1,6,(4,4))
arr2 = np.random.randint(1,6,(4,4))

In [246]:
arr1+arr2

array([[4, 5, 9, 6],
       [9, 8, 4, 2],
       [7, 7, 6, 8],
       [3, 3, 7, 2]])

In [251]:
arr1@arr2

array([[43, 44, 52, 34],
       [43, 40, 39, 24],
       [31, 24, 35, 14],
       [24, 26, 25, 19]])

In [252]:
arr1/arr2

array([[0.33333333, 1.5       , 1.25      , 5.        ],
       [0.8       , 1.        , 3.        , 1.        ],
       [1.33333333, 0.4       , 0.2       , 0.6       ],
       [0.5       , 2.        , 0.75      , 1.        ]])

In [247]:
arr1*arr2

array([[ 3,  6, 20,  5],
       [20, 16,  3,  1],
       [12, 10,  5, 15],
       [ 2,  2, 12,  1]])

In [248]:
arr1

array([[1, 3, 5, 5],
       [4, 4, 3, 1],
       [4, 2, 1, 3],
       [1, 2, 3, 1]])

In [249]:
arr2

array([[3, 2, 4, 1],
       [5, 4, 1, 1],
       [3, 5, 5, 5],
       [2, 1, 4, 1]])

In [104]:
arr1

array([[3, 3, 4, 3],
       [5, 4, 1, 4],
       [3, 4, 2, 5],
       [5, 5, 4, 3]])

In [105]:
arr2

array([[2, 2, 1, 5],
       [5, 2, 1, 1],
       [1, 2, 3, 1],
       [5, 5, 5, 4]])

In [106]:
arr1

array([[3, 3, 4, 3],
       [5, 4, 1, 4],
       [3, 4, 2, 5],
       [5, 5, 4, 3]])

In [107]:
arr2

array([[2, 2, 1, 5],
       [5, 2, 1, 1],
       [1, 2, 3, 1],
       [5, 5, 5, 4]])

In [108]:
arr1 + arr2

array([[ 5,  5,  5,  8],
       [10,  6,  2,  5],
       [ 4,  6,  5,  6],
       [10, 10,  9,  7]])

In [109]:
arr1 * arr2

array([[ 6,  6,  4, 15],
       [25,  8,  1,  4],
       [ 3,  8,  6,  5],
       [25, 25, 20, 12]])

In [110]:
arr1 + arr2

array([[ 5,  5,  5,  8],
       [10,  6,  2,  5],
       [ 4,  6,  5,  6],
       [10, 10,  9,  7]])

In [111]:
arr1+arr2

array([[ 5,  5,  5,  8],
       [10,  6,  2,  5],
       [ 4,  6,  5,  6],
       [10, 10,  9,  7]])

In [112]:
arr1-arr2

array([[ 1,  1,  3, -2],
       [ 0,  2,  0,  3],
       [ 2,  2, -1,  4],
       [ 0,  0, -1, -1]])

In [113]:
arr1*arr2

array([[ 6,  6,  4, 15],
       [25,  8,  1,  4],
       [ 3,  8,  6,  5],
       [25, 25, 20, 12]])

In [114]:
arr1

array([[3, 3, 4, 3],
       [5, 4, 1, 4],
       [3, 4, 2, 5],
       [5, 5, 4, 3]])

In [115]:
arr2

array([[2, 2, 1, 5],
       [5, 2, 1, 1],
       [1, 2, 3, 1],
       [5, 5, 5, 4]])

In [116]:
arr1

array([[3, 3, 4, 3],
       [5, 4, 1, 4],
       [3, 4, 2, 5],
       [5, 5, 4, 3]])

In [117]:
arr2

array([[2, 2, 1, 5],
       [5, 2, 1, 1],
       [1, 2, 3, 1],
       [5, 5, 5, 4]])

In [118]:
arr1@arr2

array([[40, 35, 33, 34],
       [51, 40, 32, 46],
       [53, 43, 38, 41],
       [54, 43, 37, 46]])

In [25]:
np.random.randint(1,10,(2,3))@np.random.randint(1,10,(3,4))

array([[ 58,  66,  50,  66],
       [ 95, 106,  93,  88]])

In [119]:
arr1@arr2

array([[40, 35, 33, 34],
       [51, 40, 32, 46],
       [53, 43, 38, 41],
       [54, 43, 37, 46]])

In [120]:
arr1/arr2

array([[1.5       , 1.5       , 4.        , 0.6       ],
       [1.        , 2.        , 1.        , 4.        ],
       [3.        , 2.        , 0.66666667, 5.        ],
       [1.        , 1.        , 0.8       , 0.75      ]])

In [121]:
arr1/arr2

array([[1.5       , 1.5       , 4.        , 0.6       ],
       [1.        , 2.        , 1.        , 4.        ],
       [3.        , 2.        , 0.66666667, 5.        ],
       [1.        , 1.        , 0.8       , 0.75      ]])

In [122]:
arr/0

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [123]:
arr1/0

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [124]:
#Numpy – Broadcasting.

In [125]:
arr = np.zeros((3,4))

In [126]:
arr = np.zeros((3,4))

In [127]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [128]:
arr+4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [129]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [130]:
a = np.array(range(1,5))

In [131]:
a

array([1, 2, 3, 4])

In [132]:
a = np.array([1,2,3,4])

In [133]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [134]:
a

array([1, 2, 3, 4])

In [135]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [136]:
b = np.array([[1,2,3]])

In [137]:
b

array([[1, 2, 3]])

In [138]:
b.T

array([[1],
       [2],
       [3]])

In [139]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
arr + b.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [141]:
b = np.array([[3,4,5]])

In [142]:
arr1 = arr+b.T

In [143]:
b.T

array([[3],
       [4],
       [5]])

In [144]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [145]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [146]:
np.log(arr1)

array([[1.09861229, 1.09861229, 1.09861229, 1.09861229],
       [1.38629436, 1.38629436, 1.38629436, 1.38629436],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791]])

In [147]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [148]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [149]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [150]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [151]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [152]:
np.min(arr1)

3.0

In [153]:
np.max(arr1)

5.0

In [154]:
np.min(arr1)

3.0

In [155]:
np.max(arr1)

5.0

In [253]:
arr1.T

array([[1, 4, 4, 1],
       [3, 4, 2, 2],
       [5, 3, 1, 3],
       [5, 1, 3, 1]])

In [254]:
np.min(arr)

1

In [255]:
np.max(arr)

9

In [256]:
np.sin(arr)

array([[ 0.98935825, -0.2794155 , -0.7568025 , -0.7568025 ],
       [-0.95892427,  0.84147098,  0.84147098,  0.41211849],
       [ 0.14112001,  0.90929743,  0.41211849, -0.95892427],
       [-0.95892427, -0.7568025 , -0.95892427, -0.2794155 ]])

In [257]:
np.log(arr)

array([[2.07944154, 1.79175947, 1.38629436, 1.38629436],
       [1.60943791, 0.        , 0.        , 2.19722458],
       [1.09861229, 0.69314718, 2.19722458, 1.60943791],
       [1.60943791, 1.38629436, 1.60943791, 1.79175947]])

In [259]:
np.log10(arr)

array([[0.90308999, 0.77815125, 0.60205999, 0.60205999],
       [0.69897   , 0.        , 0.        , 0.95424251],
       [0.47712125, 0.30103   , 0.95424251, 0.69897   ],
       [0.69897   , 0.60205999, 0.69897   , 0.77815125]])

In [260]:
np.exp(arr)

array([[2.98095799e+03, 4.03428793e+02, 5.45981500e+01, 5.45981500e+01],
       [1.48413159e+02, 2.71828183e+00, 2.71828183e+00, 8.10308393e+03],
       [2.00855369e+01, 7.38905610e+00, 8.10308393e+03, 1.48413159e+02],
       [1.48413159e+02, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02]])

In [262]:
np.log2(arr)

array([[3.        , 2.5849625 , 2.        , 2.        ],
       [2.32192809, 0.        , 0.        , 3.169925  ],
       [1.5849625 , 1.        , 3.169925  , 2.32192809],
       [2.32192809, 2.        , 2.32192809, 2.5849625 ]])

In [263]:
np.sqrt(arr)

array([[2.82842712, 2.44948974, 2.        , 2.        ],
       [2.23606798, 1.        , 1.        , 3.        ],
       [1.73205081, 1.41421356, 3.        , 2.23606798],
       [2.23606798, 2.        , 2.23606798, 2.44948974]])

In [264]:
np.transpose(arr)

array([[8, 5, 3, 5],
       [6, 1, 2, 4],
       [4, 1, 9, 5],
       [4, 9, 5, 6]])

In [265]:
arr.T

array([[8, 5, 3, 5],
       [6, 1, 2, 4],
       [4, 1, 9, 5],
       [4, 9, 5, 6]])

In [266]:
np.mean(arr)

4.8125

In [267]:
np.std(arr)

2.3774658252012792

In [268]:
np.median(arr)

5.0

In [273]:
pd.DataFrame(arr).mode()

     0  1  2  3
0  5.0  1  1  4
1  NaN  2  4  5
2  NaN  4  5  6
3  NaN  6  9  9

In [26]:
np.random.randint(1,5,(5,4,3,2,1))

array([[[[[2],
          [1]],

         [[1],
          [4]],

         [[4],
          [1]]],


        [[[1],
          [3]],

         [[2],
          [4]],

         [[2],
          [1]]],


        [[[1],
          [2]],

         [[1],
          [3]],

         [[3],
          [1]]],


        [[[4],
          [1]],

         [[4],
          [1]],

         [[4],
          [1]]]],



       [[[[1],
          [2]],

         [[2],
          [2]],

         [[3],
          [1]]],


        [[[1],
          [3]],

         [[2],
          [1]],

         [[4],
          [3]]],


        [[[4],
          [2]],

         [[1],
          [4]],

         [[4],
          [2]]],


        [[[3],
          [2]],

         [[4],
          [3]],

         [[4],
          [4]]]],



       [[[[4],
          [1]],

         [[3],
          [4]],

         [[4],
          [2]]],


        [[[2],
          [4]],

         [[4],
          [2]],

         [[1],
          [4]]],


        [[[2],
          [4]],

         [[3],
          [3]],

         [[1],
          [3]]],


        [[[1],
          [4]],

         [[2],
          [1]],

         [[4],
          [4]]]],



       [[[[2],
          [2]],

         [[1],
          [2]],

         [[3],
          [3]]],


        [[[4],
          [1]],

         [[2],
          [1]],

         [[3],
          [3]]],


        [[[2],
          [1]],

         [[4],
          [2]],

         [[2],
          [4]]],


        [[[3],
          [3]],

         [[3],
          [4]],

         [[4],
          [2]]]],



       [[[[2],
          [3]],

         [[4],
          [2]],

         [[3],
          [1]]],


        [[[3],
          [2]],

         [[3],
          [3]],

         [[3],
          [2]]],


        [[[4],
          [1]],

         [[4],
          [2]],

         [[4],
          [2]]],


        [[[2],
          [1]],

         [[1],
          [2]],

         [[3],
          [1]]]]])