In [2]:
#str methods: endswith, startswith, join, reverse, isupper, islower, isalnum, upper, len, lower,  isalpha, isspace, isdigit, strip-lr, 
#list methods: pop, remove, apend, extend, sort, reverse, join, index, min, max, len, copy
# tuple methods: count, index, min, max, len,
#dict methonds: update, fromkeys, pop, get, copy, keys, values, items, popitem, fromkeys,clear
#str value @ a idx is not modifiable
#tuple value @ a idx is not modiafiable (i.e immutable)
#set allows str and tuple to be part of it's emements (i.e immutable)
#set does not allow indexing and range accessing
#set methods: clear, copy, add, difference, intersection, union, issubset, issuperset, isdisjoint, symmetric_difference, pop, remove, update
#re methods: split, findall, compile, sub
# pd.read_csv, json, excel, html
# map(fn,ele) returns obj
# filter(fn,ele) returns obj
#lambda ele: opn

In [2]:
import warnings as warn
warn.filterwarnings('ignore')

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('titanic.csv')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  182 non-null    int64
 1   Name        182 non-null    object
 2   Survived    182 non-null    int64
 3   Pclass      182 non-null    int64
 4   Sex         182 non-null    int64
 5   Age         182 non-null    float64
 6   SibSp       182 non-null    int64
 7   Parch       182 non-null    int64
 8   Ticket      182 non-null    object
 9   Fare        182 non-null    float64
 10  Cabin       182 non-null    object
 11  Embarked    182 non-null    object
dtypes: float64(2), int64(6), object(4)
memory usage: 17.2+ KB

In [7]:
df[['Sex','Fare']].groupby('Sex')['Fare'].mean()

Sex
0    89.413554
1    69.124343
Name: Fare, dtype: float64

In [5]:
df.columns

Index(['Unnamed: 0', 'Name', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [47]:
# list(df['Name'])
sub1 = list(df['Name'][2:3])
sub2 = list(df['Name'][3:4])
sub1.append(sub2)
sub1

['Heikkinen, Miss. Laina', ['Futrelle, Mrs. Jacques Heath (Lily May Peel)']]

In [48]:
sub1.extend(sub2)

In [49]:
sub1

['Heikkinen, Miss. Laina',
 ['Futrelle, Mrs. Jacques Heath (Lily May Peel)'],
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)']

In [278]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [280]:
def genderChange(x):
    if x=='male': return 1
    else: return 0
df['Sex'].apply(genderChange)
df['Sex'].apply(lambda x: genderChange(x))

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [51]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [52]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [53]:
df['Name'][2:11]

2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
Name: Name, dtype: object

In [54]:
type(df['Name'])

pandas.core.series.Series

In [55]:
type(df[['Name']])

pandas.core.frame.DataFrame

In [56]:
len(df)

891

In [57]:
l = ['a','b','c','d','e','f']

In [58]:
pd.Series(l)

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object

In [59]:
li = range(1,11)
list(pd.Series(li))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [60]:
list(df['Name'])

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master. Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)',
 'Sandstrom, Miss. Marguerite Rut',
 'Bonnell, Miss. Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Vestrom, Miss. Hulda Amanda Adolfina',
 'Hewlett, Mrs. (Mary D Kingcome) ',
 'Rice, Master. Eugene',
 'Williams, Mr. Charles Eugene',
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
 'Masselmani, Mrs. Fatima',
 'Fynney, Mr. Joseph J',
 'Beesley, Mr. Lawrence',
 'McGowan, Miss. Anna "Annie"',
 'Sloper, Mr. William Thompson',
 'Palsson, Miss. Torborg Danira',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Emir, Mr. Farred Chehab',
 'Fortune, Mr. Charles Alexander',
 'O\'Dwyer, Miss. Ellen "Nellie"',
 'Todoroff, Mr. Lalio',
 'Uruchurtu, Don. Manuel E',
 'Spencer, Mrs. William Augustus (Marie Eugenie)',
 'Glynn, Miss. Mary Agatha',
 'Wheadon, Mr. Edward H',
 'Meyer, Mr. Edgar Joseph',
 'Holverson, Mr. Alexander Oskar',
 'Mamee, Mr. Hanna',
 'Cann, Mr. Ernest Charles',
 'Vander Planke, Miss. Augusta Maria',
 'Nicola-Yarred, Miss. Jamila',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
 'Kraeff, Mr. Theodor',
 'Laroche, Miss. Simonne Marie Anne Andree',
 'Devaney, Miss. Margaret Delia',
 'Rogers, Mr. William John',
 'Lennon, Mr. Denis',
 "O'Driscoll, Miss. Bridget",
 'Samaan, Mr. Youssef',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Panula, Master. Juha Niilo',
 'Nosworthy, Mr. Richard Cater',
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
 'Ostby, Mr. Engelhart Cornelius',
 'Woolner, Mr. Hugh',
 'Rugg, Miss. Emily',
 'Novel, Mr. Mansouer',
 'West, Miss. Constance Mirium',
 'Goodwin, Master. William Frederick',
 'Sirayanian, Mr. Orsen',
 'Icard, Miss. Amelie',
 'Harris, Mr. Henry Birkhardt',
 'Skoog, Master. Harald',
 'Stewart, Mr. Albert A',
 'Moubarek, Master. Gerios',
 'Nye, Mrs. (Elizabeth Ramell)',
 'Crease, Mr. Ernest James',
 'Andersson, Miss. Erna Alexandra',
 'Kink, Mr. Vincenz',
 'Jenkin, Mr. Stephen Curnow',
 'Goodwin, Miss. Lillian Amy',
 'Hood, Mr. Ambrose Jr',
 'Chronopoulos, Mr. Apostolos',
 'Bing, Mr. Lee',
 'Moen, Mr. Sigurd Hansen',
 'Staneff, Mr. Ivan',
 'Moutal, Mr. Rahamin Haim',
 'Caldwell, Master. Alden Gates',
 'Dowdell, Miss. Elizabeth',
 'Waelens, Mr. Achille',
 'Sheerlinck, Mr. Jan Baptist',
 'McDermott, Miss. Brigdet Delia',
 'Carrau, Mr. Francisco M',
 'Ilett, Miss. Bertha',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Ford, Mr. William Neal',
 'Slocovski, Mr. Selman Francis',
 'Fortune, Miss. Mabel Helen',
 'Celotti, Mr. Francesco',
 'Christmann, Mr. Emil',
 'Andreasson, Mr. Paul Edvin',
 'Chaffee, Mr. Herbert Fuller',
 'Dean, Mr. Bertram Frank',
 'Coxon, Mr. Daniel',
 'Shorney, Mr. Charles Joseph',
 'Goldschmidt, Mr. George B',
 'Greenfield, Mr. William Bertram',
 'Doling, Mrs. John T (Ada Julia Bone)',
 'Kantor, Mr. Sinai',
 'Petranec, Miss. Matilda',
 'Petroff, Mr. Pastcho ("Pentcho")',
 'White, Mr. Richard Frasar',
 'Johansson, Mr. Gustaf Joel',
 'Gustafsson, Mr. Anders Vilhelm',
 'Mionoff, Mr. Stoytcho',
 'Salkjelsvik, Miss. Anna Kristine',
 'Moss, Mr. Albert Johan',
 'Rekic, Mr. Tido',
 'Moran, Miss. Bertha',
 'Porter, Mr. Walter Chamberlain',
 'Zabour, Miss. Hileni',
 'Barton, Mr. David John',
 'Jussila, Miss. Katriina',
 'Attalah, Miss. Malake',
 'Pekoniemi, Mr. Edvard',
 'Connors, Mr. Patrick',
 'Turpin, Mr. William John Robert',
 'Baxter, Mr. Quigg Edmond',
 'Andersson, Miss. Ellis Anna Maria',
 'Hickman, Mr. Stanley George',
 'Moore, Mr. Leonard Charles',
 'Nasser, Mr. Nicholas',
 'Webber, Miss. Susan',
 'White, Mr. Percival Wayland',
 'Nicola-Yarred, Master. Elias',
 'McMahon, Mr. Martin',
 'Madsen, Mr. Fridtjof Arne',
 'Peter, Miss. Anna',
 'Ekstrom, Mr. Johan',
 'Drazenoic, Mr. Jozef',
 'Coelho, Mr. Domingos Fernandeo',
 'Robins, Mrs. Alexander A (Grace Charity Laury)',
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
 'Sobey, Mr. Samuel James Hayden',
 'Richard, Mr. Emile',
 'Newsom, Miss. Helen Monypeny',
 'Futrelle, Mr. Jacques Heath',
 'Osen, Mr. Olaf Elon',
 'Giglio, Mr. Victor',
 'Boulos, Mrs. Joseph (Sultana)',
 'Nysten, Miss. Anna Sofia',
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
 'Burke, Mr. Jeremiah',
 'Andrew, Mr. Edgardo Samuel',
 'Nicholls, Mr. Joseph Charles',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Ford, Miss. Robina Maggie "Ruby"',
 'Navratil, Mr. Michel ("Louis M Hoffman")',
 'Byles, Rev. Thomas Roussel Davids',
 'Bateman, Rev. Robert James',
 'Pears, Mrs. Thomas (Edith Wearne)',
 'Meo, Mr. Alfonzo',
 'van Billiard, Mr. Austin Blyler',
 'Olsen, Mr. Ole Martin',
 'Williams, Mr. Charles Duane',
 'Gilnagh, Miss. Katherine "Katie"',
 'Corn, Mr. Harry',
 'Smiljanic, Mr. Mile',
 'Sage, Master. Thomas Henry',
 'Cribb, Mr. John Hatfield',
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
 'Bengtsson, Mr. John Viktor',
 'Calic, Mr. Jovo',
 'Panula, Master. Eino Viljami',
 'Goldsmith, Master. Frank John William "Frankie"',
 'Chibnall, Mrs. (Edith Martha Bowerman)',
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
 'Baumann, Mr. John D',
 'Ling, Mr. Lee',
 'Van der hoef, Mr. Wyckoff',
 'Rice, Master. Arthur',
 'Johnson, Miss. Eleanor Ileen',
 'Sivola, Mr. Antti Wilhelm',
 'Smith, Mr. James Clinch',
 'Klasen, Mr. Klas Albin',
 'Lefebre, Master. Henry Forbes',
 'Isham, Miss. Ann Elizabeth',
 'Hale, Mr. Reginald',
 'Leonard, Mr. Lionel',
 'Sage, Miss. Constance Gladys',
 'Pernot, Mr. Rene',
 'Asplund, Master. Clarence Gustaf Hugo',
 'Becker, Master. Richard F',
 'Kink-Heilmann, Miss. Luise Gretchen',
 'Rood, Mr. Hugh Roscoe',
 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
 'Bourke, Mr. John',
 'Turcin, Mr. Stjepan',
 'Pinsky, Mrs. (Rosa)',
 'Carbines, Mr. William',
 'Andersen-Jensen, Miss. Carla Christine Nielsine',
 'Navratil, Master. Michel M',
 'Brown, Mrs. James Joseph (Margaret Tobin)',
 'Lurette, Miss. Elise',
 'Mernagh, Mr. Robert',
 'Olsen, Mr. Karl Siegwart Andreas',
 'Madigan, Miss. Margaret "Maggie"',
 'Yrois, Miss. Henriette ("Mrs Harbeck")',
 'Vande Walle, Mr. Nestor Cyriel',
 'Sage, Mr. Frederick',
 'Johanson, Mr. Jakob Alfred',
 'Youseff, Mr. Gerious',
 'Cohen, Mr. Gurshon "Gus"',
 'Strom, Miss. Telma Matilda',
 'Backstrom, Mr. Karl Alfred',
 'Albimona, Mr. Nassef Cassem',
 'Carr, Miss. Helen "Ellen"',
 'Blank, Mr. Henry',
 'Ali, Mr. Ahmed',
 'Cameron, Miss. Clear Annie',
 'Perkin, Mr. John Henry',
 'Givard, Mr. Hans Kristensen',
 'Kiernan, Mr. Philip',
 'Newell, Miss. Madeleine',
 'Honkanen, Miss. Eliina',
 'Jacobsohn, Mr. Sidney Samuel',
 'Bazzani, Miss. Albina',
 'Harris, Mr. Walter',
 'Sunderland, Mr. Victor Francis',
 'Bracken, Mr. James H',
 'Green, Mr. George Henry',
 'Nenkoff, Mr. Christo',
 'Hoyt, Mr. Frederick Maxfield',
 'Berglund, Mr. Karl Ivar Sven',
 'Mellors, Mr. William John',
 'Lovell, Mr. John Hall ("Henry")',
 'Fahlstrom, Mr. Arne Jonas',
 'Lefebre, Miss. Mathilde',
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
 'Larsson, Mr. Bengt Edvin',
 'Sjostedt, Mr. Ernst Adolf',
 'Asplund, Miss. Lillian Gertrud',
 'Leyson, Mr. Robert William Norman',
 'Harknett, Miss. Alice Phoebe',
 'Hold, Mr. Stephen',
 'Collyer, Miss. Marjorie "Lottie"',
 'Pengelly, Mr. Frederick William',
 'Hunt, Mr. George Henry',
 'Zabour, Miss. Thamine',
 'Murphy, Miss. Katherine "Kate"',
 'Coleridge, Mr. Reginald Charles',
 'Maenpaa, Mr. Matti Alexanteri',
 'Attalah, Mr. Sleiman',
 'Minahan, Dr. William Edward',
 'Lindahl, Miss. Agda Thorilda Viktoria',
 'Hamalainen, Mrs. William (Anna)',
 'Beckwith, Mr. Richard Leonard',
 'Carter, Rev. Ernest Courtenay',
 'Reed, Mr. James George',
 'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
 'Stead, Mr. William Thomas',
 'Lobb, Mr. William Arthur',
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
 'Touma, Mrs. Darwis (Hanne Youssef Razi)',
 'Thorne, Mrs. Gertrude Maybelle',
 'Cherry, Miss. Gladys',
 'Ward, Miss. Anna',
 'Parrish, Mrs. (Lutie Davis)',
 'Smith, Mr. Thomas',
 'Asplund, Master. Edvin Rojj Felix',
 'Taussig, Mr. Emil',
 'Harrison, Mr. William',
 'Henry, Miss. Delia',
 'Reeves, Mr. David',
 'Panula, Mr. Ernesti Arvid',
 'Persson, Mr. Ernst Ulrik',
 'Graham, Mrs. William Thompson (Edith Junkins)',
 'Bissette, Miss. Amelia',
 'Cairns, Mr. Alexander',
 'Tornquist, Mr. William Henry',
 'Mellinger, Mrs. (Elizabeth Anne Maidment)',
 'Natsch, Mr. Charles H',
 'Healy, Miss. Hanora "Nora"',
 'Andrews, Miss. Kornelia Theodosia',
 'Lindblom, Miss. Augusta Charlotta',
 'Parkes, Mr. Francis "Frank"',
 'Rice, Master. Eric',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Duane, Mr. Frank',
 'Olsson, Mr. Nils Johan Goransson',
 'de Pelsmaeker, Mr. Alfons',
 'Dorking, Mr. Edward Arthur',
 'Smith, Mr. Richard William',
 'Stankovic, Mr. Ivan',
 'de Mulder, Mr. Theodore',
 'Naidenoff, Mr. Penko',
 'Hosono, Mr. Masabumi',
 'Connolly, Miss. Kate',
 'Barber, Miss. Ellen "Nellie"',
 'Bishop, Mrs. Dickinson H (Helen Walton)',
 'Levy, Mr. Rene Jacques',
 'Haas, Miss. Aloisia',
 'Mineff, Mr. Ivan',
 'Lewy, Mr. Ervin G',
 'Hanna, Mr. Mansour',
 'Allison, Miss. Helen Loraine',
 'Saalfeld, Mr. Adolphe',
 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
 'Kelly, Miss. Anna Katherine "Annie Kate"',
 'McCoy, Mr. Bernard',
 'Johnson, Mr. William Cahoone Jr',
 'Keane, Miss. Nora A',
 'Williams, Mr. Howard Hugh "Harry"',
 'Allison, Master. Hudson Trevor',
 'Fleming, Miss. Margaret',
 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
 'Abelson, Mr. Samuel',
 'Francatelli, Miss. Laura Mabel',
 'Hays, Miss. Margaret Bechstein',
 'Ryerson, Miss. Emily Borie',
 'Lahtinen, Mrs. William (Anna Sylfven)',
 'Hendekovic, Mr. Ignjac',
 'Hart, Mr. Benjamin',
 'Nilsson, Miss. Helmina Josefina',
 'Kantor, Mrs. Sinai (Miriam Sternin)',
 'Moraweck, Dr. Ernest',
 'Wick, Miss. Mary Natalie',
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
 'Dennis, Mr. Samuel',
 'Danoff, Mr. Yoto',
 'Slayter, Miss. Hilda Mary',
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
 'Sage, Mr. George John Jr',
 'Young, Miss. Marie Grice',
 'Nysveen, Mr. Johan Hansen',
 'Ball, Mrs. (Ada E Hall)',
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
 'Hippach, Miss. Jean Gertrude',
 'McCoy, Miss. Agnes',
 'Partner, Mr. Austen',
 'Graham, Mr. George Edward',
 'Vander Planke, Mr. Leo Edmondus',
 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
 'Denkoff, Mr. Mitto',
 'Pears, Mr. Thomas Clinton',
 'Burns, Miss. Elizabeth Margaret',
 'Dahl, Mr. Karl Edwart',
 'Blackwell, Mr. Stephen Weart',
 'Navratil, Master. Edmond Roger',
 'Fortune, Miss. Alice Elizabeth',
 'Collander, Mr. Erik Gustaf',
 'Sedgwick, Mr. Charles Frederick Waddington',
 'Fox, Mr. Stanley Hubert',
 'Brown, Miss. Amelia "Mildred"',
 'Smith, Miss. Marion Elsie',
 'Davison, Mrs. Thomas Henry (Mary E Finck)',
 'Coutts, Master. William Loch "William"',
 'Dimic, Mr. Jovan',
 'Odahl, Mr. Nils Martin',
 'Williams-Lambert, Mr. Fletcher Fellows',
 'Elias, Mr. Tannous',
 'Arnold-Franchi, Mr. Josef',
 'Yousif, Mr. Wazli',
 'Vanden Steen, Mr. Leo Peter',
 'Bowerman, Miss. Elsie Edith',
 'Funk, Miss. Annie Clemmer',
 'McGovern, Miss. Mary',
 'Mockler, Miss. Helen Mary "Ellie"',
 'Skoog, Mr. Wilhelm',
 'del Carlo, Mr. Sebastiano',
 'Barbara, Mrs. (Catherine David)',
 'Asim, Mr. Adola',
 "O'Brien, Mr. Thomas",
 'Adahl, Mr. Mauritz Nils Martin',
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
 'Moussa, Mrs. (Mantoura Boulos)',
 'Jermyn, Miss. Annie',
 'Aubart, Mme. Leontine Pauline',
 'Harder, Mr. George Achilles',
 'Wiklund, Mr. Jakob Alfred',
 'Beavan, Mr. William Thomas',
 'Ringhini, Mr. Sante',
 'Palsson, Miss. Stina Viola',
 'Meyer, Mrs. Edgar Joseph (Leila Saks)',
 'Landergren, Miss. Aurora Adelia',
 'Widener, Mr. Harry Elkins',
 'Betros, Mr. Tannous',
 'Gustafsson, Mr. Karl Gideon',
 'Bidois, Miss. Rosalie',
 'Nakid, Miss. Maria ("Mary")',
 'Tikkanen, Mr. Juho',
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
 'Plotcharsky, Mr. Vasil',
 'Davies, Mr. Charles Henry',
 'Goodwin, Master. Sidney Leonard',
 'Buss, Miss. Kate',
 'Sadlier, Mr. Matthew',
 'Lehmann, Miss. Bertha',
 'Carter, Mr. William Ernest',
 'Jansson, Mr. Carl Olof',
 'Gustafsson, Mr. Johan Birger',
 'Newell, Miss. Marjorie',
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
 'Johansson, Mr. Erik',
 'Olsson, Miss. Elina',
 'McKane, Mr. Peter David',
 'Pain, Dr. Alfred',
 'Trout, Mrs. William H (Jessie L)',
 'Niskanen, Mr. Juha',
 'Adams, Mr. John',
 'Jussila, Miss. Mari Aina',
 'Hakkarainen, Mr. Pekka Pietari',
 'Oreskovic, Miss. Marija',
 'Gale, Mr. Shadrach',
 'Widegren, Mr. Carl/Charles Peter',
 'Richards, Master. William Rowe',
 'Birkeland, Mr. Hans Martin Monsen',
 'Lefebre, Miss. Ida',
 'Sdycoff, Mr. Todor',
 'Hart, Mr. Henry',
 'Minahan, Miss. Daisy E',
 'Cunningham, Mr. Alfred Fleming',
 'Sundman, Mr. Johan Julian',
 'Meek, Mrs. Thomas (Annie Louise Rowley)',
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
 'Silven, Miss. Lyyli Karoliina',
 'Matthews, Mr. William John',
 'Van Impe, Miss. Catharina',
 'Gheorgheff, Mr. Stanio',
 'Charters, Mr. David',
 'Zimmerman, Mr. Leo',
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
 'Rosblom, Mr. Viktor Richard',
 'Wiseman, Mr. Phillippe',
 'Clarke, Mrs. Charles V (Ada Maria Winfield)',
 'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',
 'Flynn, Mr. James',
 'Pickard, Mr. Berk (Berk Trembisky)',
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
 'Thorneycroft, Mrs. Percival (Florence Kate White)',
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
 'Kallio, Mr. Nikolai Erland',
 'Silvey, Mr. William Baird',
 'Carter, Miss. Lucile Polk',
 'Ford, Miss. Doolina Margaret "Daisy"',
 'Richards, Mrs. Sidney (Emily Hocking)',
 'Fortune, Mr. Mark',
 'Kvillner, Mr. Johan Henrik Johannesson',
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)',
 'Hampe, Mr. Leon',
 'Petterson, Mr. Johan Emil',
 'Reynaldo, Ms. Encarnacion',
 'Johannesen-Bratthammer, Mr. Bernt',
 'Dodge, Master. Washington',
 'Mellinger, Miss. Madeleine Violet',
 'Seward, Mr. Frederic Kimber',
 'Baclini, Miss. Marie Catherine',
 'Peuchen, Major. Arthur Godfrey',
 'West, Mr. Edwy Arthur',
 'Hagland, Mr. Ingvald Olai Olsen',
 'Foreman, Mr. Benjamin Laventall',
 'Goldenberg, Mr. Samuel L',
 'Peduzzi, Mr. Joseph',
 'Jalsevac, Mr. Ivan',
 'Millet, Mr. Francis Davis',
 'Kenyon, Mrs. Frederick R (Marion)',
 'Toomey, Miss. Ellen',
 "O'Connor, Mr. Maurice",
 'Anderson, Mr. Harry',
 'Morley, Mr. William',
 'Gee, Mr. Arthur H',
 'Milling, Mr. Jacob Christian',
 'Maisner, Mr. Simon',
 'Goncalves, Mr. Manuel Estanslas',
 'Campbell, Mr. William',
 'Smart, Mr. John Montgomery',
 'Scanlan, Mr. James',
 'Baclini, Miss. Helene Barbara',
 'Keefe, Mr. Arthur',
 'Cacic, Mr. Luka',
 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
 'Strandberg, Miss. Ida Sofia',
 'Clifford, Mr. George Quincy',
 'Renouf, Mr. Peter Henry',
 'Braund, Mr. Lewis Richard',
 'Karlsson, Mr. Nils August',
 'Hirvonen, Miss. Hildur E',
 'Goodwin, Master. Harold Victor',
 'Frost, Mr. Anthony Wood "Archie"',
 'Rouse, Mr. Richard Henry',
 'Turkula, Mrs. (Hedwig)',
 'Bishop, Mr. Dickinson H',
 'Lefebre, Miss. Jeannie',
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
 'Kent, Mr. Edward Austin',
 'Somerton, Mr. Francis William',
 'Coutts, Master. Eden Leslie "Neville"',
 'Hagland, Mr. Konrad Mathias Reiersen',
 'Windelov, Mr. Einar',
 'Molson, Mr. Harry Markland',
 'Artagaveytia, Mr. Ramon',
 'Stanley, Mr. Edward Roland',
 'Yousseff, Mr. Gerious',
 'Eustis, Miss. Elizabeth Mussey',
 'Shellard, Mr. Frederick William',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
 'Svensson, Mr. Olof',
 'Calic, Mr. Petar',
 'Canavan, Miss. Mary',
 "O'Sullivan, Miss. Bridget Mary",
 'Laitinen, Miss. Kristina Sofia',
 'Maioni, Miss. Roberta',
 'Penasco y Castellana, Mr. Victor de Satode',
 'Quick, Mrs. Frederick Charles (Jane Richards)',
 'Bradley, Mr. George ("George Arthur Brayton")',
 'Olsen, Mr. Henry Margido',
 'Lang, Mr. Fang',
 'Daly, Mr. Eugene Patrick',
 'Webber, Mr. James',
 'McGough, Mr. James Robert',
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
 'Coleff, Mr. Satio',
 'Walker, Mr. William Anderson',
 'Lemore, Mrs. (Amelia Milley)',
 'Ryan, Mr. Patrick',
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
 'Pavlovic, Mr. Stefo',
 'Perreault, Miss. Anne',
 'Vovk, Mr. Janko',
 'Lahoud, Mr. Sarkis',
 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
 'Kassem, Mr. Fared',
 'Farrell, Mr. James',
 'Ridsdale, Miss. Lucy',
 'Farthing, Mr. John',
 'Salonen, Mr. Johan Werner',
 'Hocking, Mr. Richard George',
 'Quick, Miss. Phyllis May',
 'Toufik, Mr. Nakli',
 'Elias, Mr. Joseph Jr',
 'Peter, Mrs. Catherine (Catherine Rizk)',
 'Cacic, Miss. Marija',
 'Hart, Miss. Eva Miriam',
 'Butt, Major. Archibald Willingham',
 'LeRoy, Miss. Bertha',
 'Risien, Mr. Samuel Beard',
 'Frolicher, Miss. Hedwig Margaritha',
 'Crosby, Miss. Harriet R',
 'Andersson, Miss. Ingeborg Constanzia',
 'Andersson, Miss. Sigrid Elisabeth',
 'Beane, Mr. Edward',
 'Douglas, Mr. Walter Donald',
 'Nicholson, Mr. Arthur Ernest',
 'Beane, Mrs. Edward (Ethel Clarke)',
 'Padro y Manent, Mr. Julian',
 'Goldsmith, Mr. Frank John',
 'Davies, Master. John Morgan Jr',
 'Thayer, Mr. John Borland Jr',
 'Sharp, Mr. Percival James R',
 "O'Brien, Mr. Timothy",
 'Leeni, Mr. Fahim ("Philip Zenni")',
 'Ohman, Miss. Velin',
 'Wright, Mr. George',
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
 'Robbins, Mr. Victor',
 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
 'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
 'Morrow, Mr. Thomas Rowan',
 'Sivic, Mr. Husein',
 'Norman, Mr. Robert Douglas',
 'Simmons, Mr. John',
 'Meanwell, Miss. (Marion Ogden)',
 'Davies, Mr. Alfred J',
 'Stoytcheff, Mr. Ilia',
 'Palsson, Mrs. Nils (Alma Cornelia Berglund)',
 'Doharr, Mr. Tannous',
 'Jonsson, Mr. Carl',
 'Harris, Mr. George',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Flynn, Mr. John Irwin ("Irving")',
 'Kelly, Miss. Mary',
 'Rush, Mr. Alfred George John',
 'Patchett, Mr. George',
 'Garside, Miss. Ethel',
 'Silvey, Mrs. William Baird (Alice Munger)',
 'Caram, Mrs. Joseph (Maria Elias)',
 'Jussila, Mr. Eiriik',
 'Christy, Miss. Julie Rachel',
 'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
 'Downton, Mr. William James',
 'Ross, Mr. John Hugo',
 'Paulner, Mr. Uscher',
 'Taussig, Miss. Ruth',
 'Jarvis, Mr. John Denzil',
 'Frolicher-Stehli, Mr. Maxmillian',
 'Gilinski, Mr. Eliezer',
 'Murdlin, Mr. Joseph',
 'Rintamaki, Mr. Matti',
 'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
 'Elsbury, Mr. William James',
 'Bourke, Miss. Mary',
 'Chapman, Mr. John Henry',
 'Van Impe, Mr. Jean Baptiste',
 'Leitch, Miss. Jessie Wills',
 'Johnson, Mr. Alfred',
 'Boulos, Mr. Hanna',
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
 'Slabenoff, Mr. Petco',
 'Harrington, Mr. Charles H',
 'Torber, Mr. Ernst William',
 'Homer, Mr. Harry ("Mr E Haven")',
 'Lindell, Mr. Edvard Bengtsson',
 'Karaic, Mr. Milan',
 'Daniel, Mr. Robert Williams',
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
 'Shutes, Miss. Elizabeth W',
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
 'Jardin, Mr. Jose Neto',
 'Murphy, Miss. Margaret Jane',
 'Horgan, Mr. John',
 'Brocklebank, Mr. William Alfred',
 'Herman, Miss. Alice',
 'Danbom, Mr. Ernst Gilbert',
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
 'Becker, Miss. Marion Louise',
 'Gavey, Mr. Lawrence',
 'Yasbeck, Mr. Antoni',
 'Kimball, Mr. Edwin Nelson Jr',
 'Nakid, Mr. Sahid',

In [61]:
# list(df['Name'])

In [62]:
df['Name'][2:7]

2                          Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                        Allen, Mr. William Henry
5                                Moran, Mr. James
6                         McCarthy, Mr. Timothy J
Name: Name, dtype: object

In [63]:
s = pd.Series(list(df['Name'][:5]) , index = range(1,6))

In [64]:
s

1                              Braund, Mr. Owen Harris
2    Cumings, Mrs. John Bradley (Florence Briggs Th...
3                               Heikkinen, Miss. Laina
4         Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                             Allen, Mr. William Henry
dtype: object

In [65]:
pd.Series(df['Name'][2:7], index=['a' , 'b','sudh','c' ,'d'])

a       NaN
b       NaN
sudh    NaN
c       NaN
d       NaN
Name: Name, dtype: object

In [66]:
s

1                              Braund, Mr. Owen Harris
2    Cumings, Mrs. John Bradley (Florence Briggs Th...
3                               Heikkinen, Miss. Laina
4         Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                             Allen, Mr. William Henry
dtype: object

In [67]:
s1 = list(df['Name'][5:10])

In [68]:
s+s1

1              Braund, Mr. Owen HarrisMoran, Mr. James
2    Cumings, Mrs. John Bradley (Florence Briggs Th...
3    Heikkinen, Miss. LainaPalsson, Master. Gosta L...
4    Futrelle, Mrs. Jacques Heath (Lily May Peel)Jo...
5    Allen, Mr. William HenryNasser, Mrs. Nicholas ...
dtype: object

In [69]:
# s2 = s.append(s1)

In [70]:
# s2

In [71]:
s2*2

NameError: name 's2' is not defined

In [ ]:
df

In [ ]:
df.drop('SibSp', axis=1, inplace = True)

In [ ]:
df.drop(0,inplace = True)

In [ ]:
df.head()

In [72]:
df.reset_index(inplace = True)

In [73]:
df.head()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [74]:
df.drop('PassengerId',axis=1,inplace=True)

In [75]:
df

,index,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [76]:
df.drop(3 ,axis=0,inplace=True)

In [77]:
df

,index,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [78]:
df.head()
df.drop(3,axis=0)

KeyError: '[3] not found in axis'

In [79]:
df.head()

,index,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [80]:
df.drop('index',inplace = True, axis=1)

In [81]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [82]:
df.set_index('Unnamed: 0')

KeyError: "None of ['Unnamed: 0'] are in the columns"

In [83]:
df.reset_index()

,index,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
4,5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
886,887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
887,888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
889,890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [84]:
df.dropna(inplace=True)

In [85]:
df.size ==  len(list(pd.Categorical(df['Name'])))

False

In [86]:
len(pd.Categorical(df['Name']))

182

In [87]:
df.set_index('Name',inplace=True)

In [88]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",0,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C

In [89]:
df.reset_index(inplace = True)

In [90]:
df.head(1)

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C

In [91]:
df.set_index('Name', inplace=True)

In [92]:
df.reset_index(inplace=True)

In [93]:
df.drop('index', axis=1, inplace=True)

KeyError: "['index'] not found in axis"

In [ ]:
df.loc['Heikkinen, Miss. Laina']

In [ ]:
df.set_index('Name',inplace = True)

In [ ]:
df.drop('index', axis = 1, inplace = True)

In [94]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [95]:
df.loc['Futrelle, Mrs. Jacques Heath (Lily May Peel)']

KeyError: 'Futrelle, Mrs. Jacques Heath (Lily May Peel)'

In [ ]:
df.iloc[1]

In [ ]:
df.head()

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df.head()

In [96]:
data = {'Winner' : ['Nikhil' for i in range(1,6)], 'Runner' : ['Gowtham' for i in range(1,6)]}

In [97]:
bb = pd.DataFrame(data)

In [98]:
bb.reset_index(inplace = True)

In [99]:
bb

   index  Winner   Runner
0      0  Nikhil  Gowtham
1      1  Nikhil  Gowtham
2      2  Nikhil  Gowtham
3      3  Nikhil  Gowtham
4      4  Nikhil  Gowtham

In [100]:
d = {"key1":[2,3,4,5 ],
     "key2":[4,5,6,7],
     "key3":[2,3,4,5]}

In [101]:
pd.DataFrame(d)

   key1  key2  key3
0     2     4     2
1     3     5     3
2     4     6     4
3     5     7     5

In [102]:
d1 = {"key1":(2,3,4,5 ),
     "key2":(4,5,6,7),
     "key3":(2,3,4,5)}

In [103]:
pd.DataFrame(d1)

   key1  key2  key3
0     2     4     2
1     3     5     3
2     4     6     4
3     5     7     5

In [104]:
df1 = pd.read_csv("taxonomy.csv")

In [105]:
df1.head()

  taxonomy_id                     name parent_id     parent_name
0         101                Emergency       NaN             NaN
1      101-01        Disaster Response       101       Emergency
2      101-02           Emergency Cash       101       Emergency
3   101-02-01        Help Pay for Food    101-02  Emergency Cash
4   101-02-02  Help Pay for Healthcare    101-02  Emergency Cash

In [106]:
df1.shape

(290, 4)

In [107]:
df1.size

1160

In [108]:
df1.dropna()

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [109]:
pd.Categorical(df1['parent_name'])

[NaN, 'Emergency', 'Emergency', 'Emergency Cash', 'Emergency Cash', ..., 'Advocacy & Legal Aid', 'Legal', 'Legal', 'Legal', 'Legal']
Length: 290
Categories (50, object): ['Addiction & Recovery', 'Adoption & Foster Care', 'Advocacy & Legal Aid', 'Baby Supplies', ..., 'Support Network', 'Transit', 'Transportation', 'Work']

In [110]:
pd.Categorical(df1['parent_id'])

[NaN, '101', '101', '101-02', '101-02', ..., '111-01', '111', '111', '111', '111']
Length: 290
Categories (60, object): ['101', '101-02', '101-06', '102', ..., '110-03', '111', '111-01', '111-01-01']

In [111]:
df1.dropna(axis=1)

    taxonomy_id                          name
0           101                     Emergency
1        101-01             Disaster Response
2        101-02                Emergency Cash
3     101-02-01             Help Pay for Food
4     101-02-02       Help Pay for Healthcare
..          ...                           ...
285   111-01-07              Workplace Rights
286      111-02                     Mediation
287      111-03                        Notary
288      111-04                Representation
289      111-05  Translation & Interpretation

[290 rows x 2 columns]

In [112]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [113]:
df1.fillna("sudh",inplace=True)

In [114]:
df1.dtypes

taxonomy_id    object
name           object
parent_id      object
parent_name    object
dtype: object

In [115]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency      sudh                  sudh
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [116]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [117]:
df.dropna(axis=0)

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...
177,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,1,1,11751,52.5542,D35,S
178,"Carlsson, Mr. Frans Olof",0,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
179,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,0,1,11767,83.1583,C50,C
180,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
181,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C

In [118]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [119]:
df.dropna(axis=1)

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...
177,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,1,1,11751,52.5542,D35,S
178,"Carlsson, Mr. Frans Olof",0,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
179,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,0,1,11767,83.1583,C50,C
180,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
181,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C

In [120]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [121]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [122]:
df.dtypes

Name         object
Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object

In [123]:
df[df.dtypes[df.dtypes != 'object'].index].columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [124]:
num_cols = [col for col in list(df.columns) if (type(df[col]) == int) | (type(df[col]) == float)]

In [125]:
num_cols

[]

In [126]:
df.columns

Index(['Name', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [127]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [128]:
df[df.dtypes[df.dtypes != 'object'].index].groupby('Survived').mean()

            Pclass        Age     SibSp     Parch       Fare
Survived
0         1.216667  41.350000  0.366667  0.450000  64.048262
1         1.180328  32.888689  0.508197  0.491803  86.089312

In [173]:
df[df.dtypes[(df.dtypes == 'int') | (df.dtypes == 'float')].index].groupby('Survived').mean()

            Pclass        Age     SibSp     Parch       Fare
Survived
0         1.216667  41.350000  0.366667  0.450000  64.048262
1         1.180328  32.888689  0.508197  0.491803  86.089312

In [174]:
df.dtypes

Name         object
Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object

In [175]:
df[df.dtypes[(df.dtypes == 'int') | (df.dtypes == 'float')].index].groupby('Survived').sum()

          Pclass      Age  SibSp  Parch        Fare
Survived
0             73  2481.00     22     27   3842.8957
1            144  4012.42     62     60  10502.8961

In [176]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [177]:
df.groupby('Sex').sum()['Fare']

Sex
female    7778.9792
male      6566.8126
Name: Fare, dtype: float64

In [179]:
df[df.dtypes[(df.dtypes == 'int') | (df.dtypes == 'float')].index].groupby('Survived').mean()

            Pclass        Age     SibSp     Parch       Fare
Survived
0         1.216667  41.350000  0.366667  0.450000  64.048262
1         1.180328  32.888689  0.508197  0.491803  86.089312

In [183]:
df.dtypes[(df.dtypes == 'int') | (df.dtypes == 'float')].index

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [192]:
def getGender(gender):
    if gender== 'male': 
        return 1
    else: return 0

In [195]:
df.drop('sex', axis=1, inplace=True)

In [196]:
df['Sex'] = df['Sex'].apply(lambda x: getGender(x))

In [198]:
df[df.dtypes[(df.dtypes == 'int') | (df.dtypes == 'float')].index].groupby('Sex').mean()

     Survived    Pclass        Age     SibSp     Parch       Fare
Sex
0    0.931034  1.218391  32.649425  0.528736  0.551724  89.413554
1    0.431579  1.168421  38.451789  0.400000  0.410526  69.124343

In [159]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [167]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,male,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,female,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,male,34.0,0,0,248698,13.0000,D56,S

In [199]:
df.groupby('Pclass').sum()

,Name,Survived,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",105,84,5904.42,76,74,PC 175991746311378311378819950PC 1757211350936...,13958.8501,C85E46C103A6C23 C25 C27D33B30C83C23 C25 C27E31...,CSSSSCCSSSCCSSCSSSCSSCCCCCCCSSQSSSSSSSCSCSCSCC...
2,"Beesley, Mr. LawrenceNye, Mrs. (Elizabeth Rame...",12,6,379.00,6,6,248698C.A. 2939527267230080230136230080SC/Pari...,276.6667,D56F33E101F2F4F2DDF2F33DF33F4E101E77,SSSSSSCSSSCSSSS
3,"Sandstrom, Miss. Marguerite RutMoen, Mr. Sigur...",5,5,210.00,2,7,PP 9549348123347054347054PP 9549SOTON/O.Q. 392...,110.2750,G6F G73G6G6G6E10F G63F G73E121E121,SSSSSSSSSS

In [215]:
df['Pclass'].unique()

array([1, 3, 2])

In [200]:
df3 = df.groupby('Pclass').sum()

In [201]:
df3

,Name,Survived,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",105,84,5904.42,76,74,PC 175991746311378311378819950PC 1757211350936...,13958.8501,C85E46C103A6C23 C25 C27D33B30C83C23 C25 C27E31...,CSSSSCCSSSCCSSCSSSCSSCCCCCCCSSQSSSSSSSCSCSCSCC...
2,"Beesley, Mr. LawrenceNye, Mrs. (Elizabeth Rame...",12,6,379.00,6,6,248698C.A. 2939527267230080230136230080SC/Pari...,276.6667,D56F33E101F2F4F2DDF2F33DF33F4E101E77,SSSSSSCSSSCSSSS
3,"Sandstrom, Miss. Marguerite RutMoen, Mr. Sigur...",5,5,210.00,2,7,PP 9549348123347054347054PP 9549SOTON/O.Q. 392...,110.2750,G6F G73G6G6G6E10F G63F G73E121E121,SSSSSSSSSS

In [202]:
df3

,Name,Survived,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",105,84,5904.42,76,74,PC 175991746311378311378819950PC 1757211350936...,13958.8501,C85E46C103A6C23 C25 C27D33B30C83C23 C25 C27E31...,CSSSSCCSSSCCSSCSSSCSSCCCCCCCSSQSSSSSSSCSCSCSCC...
2,"Beesley, Mr. LawrenceNye, Mrs. (Elizabeth Rame...",12,6,379.00,6,6,248698C.A. 2939527267230080230136230080SC/Pari...,276.6667,D56F33E101F2F4F2DDF2F33DF33F4E101E77,SSSSSSCSSSCSSSS
3,"Sandstrom, Miss. Marguerite RutMoen, Mr. Sigur...",5,5,210.00,2,7,PP 9549348123347054347054PP 9549SOTON/O.Q. 392...,110.2750,G6F G73G6G6G6E10F G63F G73E121E121,SSSSSSSSSS

In [203]:
df3.T

Pclass,1,2,3
Name,"Cumings, Mrs. John Bradley (Florence Briggs Th...","Beesley, Mr. LawrenceNye, Mrs. (Elizabeth Rame...","Sandstrom, Miss. Marguerite RutMoen, Mr. Sigur..."
Survived,105,12,5
Sex,84,6,5
Age,5904.42,379.0,210.0
SibSp,76,6,2
Parch,74,6,7
Ticket,PC 175991746311378311378819950PC 1757211350936...,248698C.A. 2939527267230080230136230080SC/Pari...,PP 9549348123347054347054PP 9549SOTON/O.Q. 392...
Fare,13958.8501,276.6667,110.275
Cabin,C85E46C103A6C23 C25 C27D33B30C83C23 C25 C27E31...,D56F33E101F2F4F2DDF2F33DF33F4E101E77,G6F G73G6G6G6E10F G63F G73E121E121
Embarked,CSSSSCCSSSCCSSCSSSCSSCCCCCCCSSQSSSSSSSCSCSCSCC...,SSSSSSCSSSCSSSS,SSSSSSSSSS

In [204]:
df3.transpose()

Pclass,1,2,3
Name,"Cumings, Mrs. John Bradley (Florence Briggs Th...","Beesley, Mr. LawrenceNye, Mrs. (Elizabeth Rame...","Sandstrom, Miss. Marguerite RutMoen, Mr. Sigur..."
Survived,105,12,5
Sex,84,6,5
Age,5904.42,379.0,210.0
SibSp,76,6,2
Parch,74,6,7
Ticket,PC 175991746311378311378819950PC 1757211350936...,248698C.A. 2939527267230080230136230080SC/Pari...,PP 9549348123347054347054PP 9549SOTON/O.Q. 392...
Fare,13958.8501,276.6667,110.275
Cabin,C85E46C103A6C23 C25 C27D33B30C83C23 C25 C27E31...,D56F33E101F2F4F2DDF2F33DF33F4E101E77,G6F G73G6G6G6E10F G63F G73E121E121
Embarked,CSSSSCCSSSCCSSCSSSCSSCCCCCCCSSQSSSSSSSCSCSCSCC...,SSSSSSCSSSCSSSS,SSSSSSSSSS

In [205]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,172,173,174,175,176,177,178,179,180,181
Name,"Cumings, Mrs. John Bradley (Florence Briggs Th...","McCarthy, Mr. Timothy J","Sandstrom, Miss. Marguerite Rut","Bonnell, Miss. Elizabeth","Beesley, Mr. Lawrence","Sloper, Mr. William Thompson","Fortune, Mr. Charles Alexander","Harper, Mrs. Henry Sleeper (Myna Haxtun)","Ostby, Mr. Engelhart Cornelius","Harris, Mr. Henry Birkhardt",...,"Compton, Miss. Sara Rebecca","Lines, Miss. Mary Conover","Daly, Mr. Peter Denis","Swift, Mrs. Frederick Joel (Margaret Welles Ba...","Roebling, Mr. Washington Augustus II","Beckwith, Mrs. Richard Leonard (Sallie Monypeny)","Carlsson, Mr. Frans Olof","Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)","Graham, Miss. Margaret Edith","Behr, Mr. Karl Howell"
Survived,1,0,1,1,1,1,0,1,0,0,...,1,1,1,1,0,1,0,1,1,1
Pclass,1,1,3,1,2,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Sex,0,1,0,0,1,1,1,0,1,1,...,0,0,1,0,1,0,1,0,0,1
Age,38.0,54.0,4.0,58.0,34.0,28.0,19.0,49.0,65.0,45.0,...,39.0,16.0,51.0,48.0,31.0,47.0,33.0,56.0,19.0,26.0
SibSp,1,0,1,0,0,0,3,1,0,1,...,1,0,0,0,0,1,0,0,0,0
Parch,0,0,1,0,0,0,2,0,1,0,...,1,1,0,0,0,1,0,1,0,0
Ticket,PC 17599,17463,PP 9549,113783,248698,113788,19950,PC 17572,113509,36973,...,PC 17756,PC 17592,113055,17466,PC 17590,11751,695,11767,112053,111369
Fare,71.2833,51.8625,16.7,26.55,13.0,35.5,263.0,76.7292,61.9792,83.475,...,83.1583,39.4,26.55,25.9292,50.4958,52.5542,5.0,83.1583,30.0,30.0
Cabin,C85,E46,G6,C103,D56,A6,C23 C25 C27,D33,B30,C83,...,E49,D28,E17,D17,A24,D35,B51 B53 B55,C50,B42,C148
Embarked,C,S,S,S,S,S,S,C,C,S,...,C,S,S,S,S,S,S,C,S,C

In [206]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,0,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,1,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,0,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,0,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,1,34.0,0,0,248698,13.0000,D56,S

In [207]:
df.to_csv('titanic.csv')

In [208]:
df11 = df[['Name','Survived','Pclass']][0:5]

In [209]:
df11

                                                Name  Survived  Pclass
0  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
1                            McCarthy, Mr. Timothy J         0       1
2                    Sandstrom, Miss. Marguerite Rut         1       3
3                           Bonnell, Miss. Elizabeth         1       1
4                              Beesley, Mr. Lawrence         1       2

In [210]:
df12 = df[['Name','Survived','Pclass']][5:10]

In [211]:
df12

                                       Name  Survived  Pclass
5              Sloper, Mr. William Thompson         1       1
6            Fortune, Mr. Charles Alexander         0       1
7  Harper, Mrs. Henry Sleeper (Myna Haxtun)         1       1
8            Ostby, Mr. Engelhart Cornelius         0       1
9               Harris, Mr. Henry Birkhardt         0       1

In [212]:
df11

                                                Name  Survived  Pclass
0  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
1                            McCarthy, Mr. Timothy J         0       1
2                    Sandstrom, Miss. Marguerite Rut         1       3
3                           Bonnell, Miss. Elizabeth         1       1
4                              Beesley, Mr. Lawrence         1       2

In [213]:
df12

                                       Name  Survived  Pclass
5              Sloper, Mr. William Thompson         1       1
6            Fortune, Mr. Charles Alexander         0       1
7  Harper, Mrs. Henry Sleeper (Myna Haxtun)         1       1
8            Ostby, Mr. Engelhart Cornelius         0       1
9               Harris, Mr. Henry Birkhardt         0       1

In [149]:
pd.concat([df11,df12],axis=1)

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,NaN,NaN,NaN
1,"McCarthy, Mr. Timothy J",0.0,1.0,NaN,NaN,NaN
2,"Sandstrom, Miss. Marguerite Rut",1.0,3.0,NaN,NaN,NaN
3,"Bonnell, Miss. Elizabeth",1.0,1.0,NaN,NaN,NaN
4,"Beesley, Mr. Lawrence",1.0,2.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Sloper, Mr. William Thompson",1.0,1.0
6,NaN,NaN,NaN,"Fortune, Mr. Charles Alexander",0.0,1.0
7,NaN,NaN,NaN,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",1.0,1.0
8,NaN,NaN,NaN,"Ostby, Mr. Engelhart Cornelius",0.0,1.0
9,NaN,NaN,NaN,"Harris, Mr. Henry Birkhardt",0.0,1.0

In [150]:
pd.concat([df11,df12],axis = 0)

                                                Name  Survived  Pclass
0  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
1                            McCarthy, Mr. Timothy J         0       1
2                    Sandstrom, Miss. Marguerite Rut         1       3
3                           Bonnell, Miss. Elizabeth         1       1
4                              Beesley, Mr. Lawrence         1       2
5                       Sloper, Mr. William Thompson         1       1
6                     Fortune, Mr. Charles Alexander         0       1
7           Harper, Mrs. Henry Sleeper (Myna Haxtun)         1       1
8                     Ostby, Mr. Engelhart Cornelius         0       1
9                        Harris, Mr. Henry Birkhardt         0       1

In [151]:
df5 = pd.concat([df11,df12],axis=1)

In [152]:
df5 = df5.fillna("sudh")

In [153]:
df5

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,sudh,sudh,sudh
1,"McCarthy, Mr. Timothy J",0.0,1.0,sudh,sudh,sudh
2,"Sandstrom, Miss. Marguerite Rut",1.0,3.0,sudh,sudh,sudh
3,"Bonnell, Miss. Elizabeth",1.0,1.0,sudh,sudh,sudh
4,"Beesley, Mr. Lawrence",1.0,2.0,sudh,sudh,sudh
5,sudh,sudh,sudh,"Sloper, Mr. William Thompson",1.0,1.0
6,sudh,sudh,sudh,"Fortune, Mr. Charles Alexander",0.0,1.0
7,sudh,sudh,sudh,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",1.0,1.0
8,sudh,sudh,sudh,"Ostby, Mr. Engelhart Cornelius",0.0,1.0
9,sudh,sudh,sudh,"Harris, Mr. Henry Birkhardt",0.0,1.0

In [260]:
data1 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key2':[4,5,6,7,8],
                      'key3':[3,4,5,6,6]
})

In [261]:
data2 = pd.DataFrame({'key1':[1,2,45,6,67],
                      'key4':[56,5,6,7,8],
                      'key5':[3,56,5,6,6]
}
)

In [262]:
data1.join(data2)

ValueError: columns overlap but no suffix specified: Index(['key1'], dtype='object')

In [233]:
pd.merge(data1,data2)

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [234]:
pd.merge(data1,data2, how='outer')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [235]:
pd.merge(data1,data2, how='left')

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [236]:
pd.merge(data1,data2, how='right')

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    67   NaN   NaN     8     6

In [245]:
pd.concat([data1,data2], axis=1)

   key1  key2  key3  key1  key4  key5
0     1     4     3     1    56     3
1     2     5     4     2     5    56
2     4     6     5    45     6     5
3     5     7     6     6     7     6
4     6     8     6    67     8     6

In [242]:
pd.merge(data1,data2, how ='outer', left_on='key1', right_on='key4')

   key1_x  key2  key3  key1_y  key4  key5
0     1.0   4.0   3.0     NaN   NaN   NaN
1     2.0   5.0   4.0     NaN   NaN   NaN
2     4.0   6.0   5.0     NaN   NaN   NaN
3     5.0   7.0   6.0     2.0   5.0  56.0
4     6.0   8.0   6.0    45.0   6.0   5.0
5     NaN   NaN   NaN     6.0   7.0   6.0
6     NaN   NaN   NaN    67.0   8.0   6.0
7     NaN   NaN   NaN     1.0  56.0   3.0

In [156]:
data1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [78]:
data2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [220]:
pd.concat([df11,df12],axis=0)

                                                Name  Survived  Pclass
0  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
1                            McCarthy, Mr. Timothy J         0       1
2                    Sandstrom, Miss. Marguerite Rut         1       3
3                           Bonnell, Miss. Elizabeth         1       1
4                              Beesley, Mr. Lawrence         1       2
5                       Sloper, Mr. William Thompson         1       1
6                     Fortune, Mr. Charles Alexander         0       1
7           Harper, Mrs. Henry Sleeper (Myna Haxtun)         1       1
8                     Ostby, Mr. Engelhart Cornelius         0       1
9                        Harris, Mr. Henry Birkhardt         0       1

In [221]:
pd.concat([df11,df12],axis=1)

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,NaN,NaN,NaN
1,"McCarthy, Mr. Timothy J",0.0,1.0,NaN,NaN,NaN
2,"Sandstrom, Miss. Marguerite Rut",1.0,3.0,NaN,NaN,NaN
3,"Bonnell, Miss. Elizabeth",1.0,1.0,NaN,NaN,NaN
4,"Beesley, Mr. Lawrence",1.0,2.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Sloper, Mr. William Thompson",1.0,1.0
6,NaN,NaN,NaN,"Fortune, Mr. Charles Alexander",0.0,1.0
7,NaN,NaN,NaN,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",1.0,1.0
8,NaN,NaN,NaN,"Ostby, Mr. Engelhart Cornelius",0.0,1.0
9,NaN,NaN,NaN,"Harris, Mr. Henry Birkhardt",0.0,1.0

In [222]:
pd.merge(data1,data2,how='outer')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [223]:
pd.merge(data1, data2)

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [25]:
pd.merge(data1,data2)

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [29]:
pd.merge(data1, data2, how = 'left')

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [30]:
pd.merge(data1,data2, how = 'right')

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    67   NaN   NaN     8     6

In [33]:
pd.merge(data1, data2, how = 'outer')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [36]:
pd.merge(data1, data2, how = 'cross')

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       6     7     6
4        1     4     3      67     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       6     7     6
9        2     5     4      67     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       6     7     6
14       4     6     5      67     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       6     7     6
19       5     7     6      67     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       6     7     6
24       6     8     6      67     8     6

In [202]:
pd.merge(data1,data2,how = 'left')

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [203]:
data1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [204]:
pd.merge(data1,data2,how = 'right')

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    67   NaN   NaN     8     6

In [111]:
pd.merge(data1,data2,how = 'outer')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [35]:
pd.merge(data1,data2,how = 'cross')

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       6     7     6
4        1     4     3      67     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       6     7     6
9        2     5     4      67     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       6     7     6
14       4     6     5      67     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       6     7     6
19       5     7     6      67     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       6     7     6
24       6     8     6      67     8     6

In [209]:
data1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [210]:
data2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [39]:
data1.columns

Index(['key1', 'key2', 'key3'], dtype='object')

In [40]:
data2.columns

Index(['key1', 'key4', 'key5'], dtype='object')

In [44]:
pd.merge(data1, data2, how = 'outer', left_on = 'key1', right_on = 'key4')

   key1_x  key2  key3  key1_y  key4  key5
0     1.0   4.0   3.0     NaN   NaN   NaN
1     2.0   5.0   4.0     NaN   NaN   NaN
2     4.0   6.0   5.0     NaN   NaN   NaN
3     5.0   7.0   6.0     2.0   5.0  56.0
4     6.0   8.0   6.0    45.0   6.0   5.0
5     NaN   NaN   NaN     6.0   7.0   6.0
6     NaN   NaN   NaN    67.0   8.0   6.0
7     NaN   NaN   NaN     1.0  56.0   3.0

In [42]:
pd.merge(data1, data2, how = 'left', left_on = 'key1' , right_on = 'key4')

   key1_x  key2  key3  key1_y  key4  key5
0       1     4     3     NaN   NaN   NaN
1       2     5     4     NaN   NaN   NaN
2       4     6     5     NaN   NaN   NaN
3       5     7     6     2.0   5.0  56.0
4       6     8     6    45.0   6.0   5.0

In [211]:
pd.merge(data1,data2,how = 'left' , left_on='key2' , right_on= 'key4' )

   key1_x  key2  key3  key1_y  key4  key5
0       1     4     3     NaN   NaN   NaN
1       2     5     4     2.0   5.0  56.0
2       4     6     5    45.0   6.0   5.0
3       5     7     6     6.0   7.0   6.0
4       6     8     6    67.0   8.0   6.0

In [274]:
data1 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key2':[4,5,6,7,8],
                      'key3':[3,4,5,6,6]},
                     index = ['a','b','c','d','e']
)

In [265]:
data2 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key22':[4,5,6,7,8],
                      'key33':[3,4,5,6,6]
},index=['a','b','h','i','j']
)

In [275]:
data2 = pd.DataFrame({'key11':[1,2,4,5,6],
                      'key22':[4,5,6,7,8],
                      'key33':[3,4,5,6,6]
},index=['a','b','h','i','j']
)

In [269]:
data1.join(data2)

   key1  key2  key3  key11  key22  key33
a     1     4     3    1.0    4.0    3.0
b     2     5     4    2.0    5.0    4.0
c     4     6     5    NaN    NaN    NaN
d     5     7     6    NaN    NaN    NaN
e     6     8     6    NaN    NaN    NaN

In [276]:
data1.join(data2, how='cross')

    key1  key2  key3  key11  key22  key33
0      1     4     3      1      4      3
1      1     4     3      2      5      4
2      1     4     3      4      6      5
3      1     4     3      5      7      6
4      1     4     3      6      8      6
5      2     5     4      1      4      3
6      2     5     4      2      5      4
7      2     5     4      4      6      5
8      2     5     4      5      7      6
9      2     5     4      6      8      6
10     4     6     5      1      4      3
11     4     6     5      2      5      4
12     4     6     5      4      6      5
13     4     6     5      5      7      6
14     4     6     5      6      8      6
15     5     7     6      1      4      3
16     5     7     6      2      5      4
17     5     7     6      4      6      5
18     5     7     6      5      7      6
19     5     7     6      6      8      6
20     6     8     6      1      4      3
21     6     8     6      2      5      4
22     6     8     6      4      6      5
23     6     8     6      5      7      6
24     6     8     6      6      8      6

In [277]:
pd.merge(data1,data2, how='cross')

    key1  key2  key3  key11  key22  key33
0      1     4     3      1      4      3
1      1     4     3      2      5      4
2      1     4     3      4      6      5
3      1     4     3      5      7      6
4      1     4     3      6      8      6
5      2     5     4      1      4      3
6      2     5     4      2      5      4
7      2     5     4      4      6      5
8      2     5     4      5      7      6
9      2     5     4      6      8      6
10     4     6     5      1      4      3
11     4     6     5      2      5      4
12     4     6     5      4      6      5
13     4     6     5      5      7      6
14     4     6     5      6      8      6
15     5     7     6      1      4      3
16     5     7     6      2      5      4
17     5     7     6      4      6      5
18     5     7     6      5      7      6
19     5     7     6      6      8      6
20     6     8     6      1      4      3
21     6     8     6      2      5      4
22     6     8     6      4      6      5
23     6     8     6      5      7      6
24     6     8     6      6      8      6

In [270]:
data2.join(data1)

   key11  key22  key33  key1  key2  key3
a      1      4      3   1.0   4.0   3.0
b      2      5      4   2.0   5.0   4.0
h      4      6      5   NaN   NaN   NaN
i      5      7      6   NaN   NaN   NaN
j      6      8      6   NaN   NaN   NaN

In [230]:
pd.merge(data1,data2)

   key1  key2  key3  key22  key33
0     1     4     3      4      3
1     2     5     4      5      4
2     4     6     5      6      5
3     5     7     6      7      6
4     6     8     6      8      6

In [70]:
data1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [71]:
data2

   key11  key22  key33
a      1      4      3
b      2      5      4
h      4      6      5
i      5      7      6
j      6      8      6

In [72]:
data1.join(data2)

   key1  key2  key3  key11  key22  key33
a     1     4     3    1.0    4.0    3.0
b     2     5     4    2.0    5.0    4.0
c     4     6     5    NaN    NaN    NaN
d     5     7     6    NaN    NaN    NaN
e     6     8     6    NaN    NaN    NaN

In [273]:
data1.join(data2, how='right')

   key1  key2  key3  key11  key22  key33
a   1.0   4.0   3.0      1      4      3
b   2.0   5.0   4.0      2      5      4
h   NaN   NaN   NaN      4      6      5
i   NaN   NaN   NaN      5      7      6
j   NaN   NaN   NaN      6      8      6

In [58]:
pd.merge(data1, data2, left_on = 'key1', right_on = 'key11')

   key1  key2  key3  key11  key22  key33
0     1     4     3      1      4      3
1     2     5     4      2      5      4
2     4     6     5      4      6      5
3     5     7     6      5      7      6
4     6     8     6      6      8      6

In [56]:
data1.join(data2, how = 'inner')

   key1  key2  key3  key11  key22  key33
a     1     4     3      1      4      3
b     2     5     4      2      5      4

In [59]:
data1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [60]:
data2

   key11  key22  key33
a      1      4      3
b      2      5      4
h      4      6      5
i      5      7      6
j      6      8      6

In [254]:
data1.join(data2)

   key1  key2  key3  key11  key22  key33
a     1     4     3    1.0    4.0    3.0
b     2     5     4    2.0    5.0    4.0
c     4     6     5    NaN    NaN    NaN
d     5     7     6    NaN    NaN    NaN
e     6     8     6    NaN    NaN    NaN

In [259]:
data1.join(data2, how='right')

   key1  key2  key3  key11  key22  key33
a   1.0   4.0   3.0      1      4      3
b   2.0   5.0   4.0      2      5      4
h   NaN   NaN   NaN      4      6      5
i   NaN   NaN   NaN      5      7      6
j   NaN   NaN   NaN      6      8      6

In [62]:
data1.join(data2)

   key1  key2  key3  key11  key22  key33
a     1     4     3    1.0    4.0    3.0
b     2     5     4    2.0    5.0    4.0
c     4     6     5    NaN    NaN    NaN
d     5     7     6    NaN    NaN    NaN
e     6     8     6    NaN    NaN    NaN

In [64]:
data1.join(data2, how = 'left')

   key1  key2  key3  key11  key22  key33
a     1     4     3    1.0    4.0    3.0
b     2     5     4    2.0    5.0    4.0
c     4     6     5    NaN    NaN    NaN
d     5     7     6    NaN    NaN    NaN
e     6     8     6    NaN    NaN    NaN

In [218]:
data1.join(data2,how='right')

   key1  key2  key3  key11  key22  key33
a   1.0   4.0   3.0      1      4      3
b   2.0   5.0   4.0      2      5      4
h   NaN   NaN   NaN      4      6      5
i   NaN   NaN   NaN      5      7      6
j   NaN   NaN   NaN      6      8      6

In [90]:
# pd.merge(data1, data2)

In [66]:
data1.join(data2)

   key1  key2  key3  key11  key22  key33
a     1     4     3    1.0    4.0    3.0
b     2     5     4    2.0    5.0    4.0
c     4     6     5    NaN    NaN    NaN
d     5     7     6    NaN    NaN    NaN
e     6     8     6    NaN    NaN    NaN

In [67]:
data1.join(data2,how = 'right')

   key1  key2  key3  key11  key22  key33
a   1.0   4.0   3.0      1      4      3
b   2.0   5.0   4.0      2      5      4
h   NaN   NaN   NaN      4      6      5
i   NaN   NaN   NaN      5      7      6
j   NaN   NaN   NaN      6      8      6

In [68]:
data1.join(data2, how = 'cross')

    key1  key2  key3  key11  key22  key33
0      1     4     3      1      4      3
1      1     4     3      2      5      4
2      1     4     3      4      6      5
3      1     4     3      5      7      6
4      1     4     3      6      8      6
5      2     5     4      1      4      3
6      2     5     4      2      5      4
7      2     5     4      4      6      5
8      2     5     4      5      7      6
9      2     5     4      6      8      6
10     4     6     5      1      4      3
11     4     6     5      2      5      4
12     4     6     5      4      6      5
13     4     6     5      5      7      6
14     4     6     5      6      8      6
15     5     7     6      1      4      3
16     5     7     6      2      5      4
17     5     7     6      4      6      5
18     5     7     6      5      7      6
19     5     7     6      6      8      6
20     6     8     6      1      4      3
21     6     8     6      2      5      4
22     6     8     6      4      6      5
23     6     8     6      5      7      6
24     6     8     6      6      8      6

In [69]:
data1.join(data2,how='outer')

   key1  key2  key3  key11  key22  key33
a   1.0   4.0   3.0    1.0    4.0    3.0
b   2.0   5.0   4.0    2.0    5.0    4.0
c   4.0   6.0   5.0    NaN    NaN    NaN
d   5.0   7.0   6.0    NaN    NaN    NaN
e   6.0   8.0   6.0    NaN    NaN    NaN
h   NaN   NaN   NaN    4.0    6.0    5.0
i   NaN   NaN   NaN    5.0    7.0    6.0
j   NaN   NaN   NaN    6.0    8.0    6.0

In [220]:
data1.join(data2,how='cross')

    key1  key2  key3  key11  key22  key33
0      1     4     3      1      4      3
1      1     4     3      2      5      4
2      1     4     3      4      6      5
3      1     4     3      5      7      6
4      1     4     3      6      8      6
5      2     5     4      1      4      3
6      2     5     4      2      5      4
7      2     5     4      4      6      5
8      2     5     4      5      7      6
9      2     5     4      6      8      6
10     4     6     5      1      4      3
11     4     6     5      2      5      4
12     4     6     5      4      6      5
13     4     6     5      5      7      6
14     4     6     5      6      8      6
15     5     7     6      1      4      3
16     5     7     6      2      5      4
17     5     7     6      4      6      5
18     5     7     6      5      7      6
19     5     7     6      6      8      6
20     6     8     6      1      4      3
21     6     8     6      2      5      4
22     6     8     6      4      6      5
23     6     8     6      5      7      6
24     6     8     6      6      8      6

In [70]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [71]:
df['Fare_INR'] = df['Fare'].apply(lambda x: x*80)

In [225]:
df["Fare_inr"] = df['Fare'].apply(lambda x : x*80)

In [72]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4248.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,644.000

In [227]:
df["len_name"] = df['Name'].apply(len)

In [73]:
df['Sex'] = df['Sex'].apply(lambda x: 1 if x == 'Male' else 0)

In [74]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,5702.664
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,4248.000
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,644.000

In [229]:
def inr_con(x):
    return x*80

df["Fare_inr"] = df['Fare'].apply(inr_con)

In [224]:
df.head()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,0,38.0,1,0,PC 17599,71.2833,C85,C
1,"McCarthy, Mr. Timothy J",0,1,1,54.0,0,0,17463,51.8625,E46,S
2,"Sandstrom, Miss. Marguerite Rut",1,3,0,4.0,1,1,PP 9549,16.7000,G6,S
3,"Bonnell, Miss. Elizabeth",1,1,0,58.0,0,0,113783,26.5500,C103,S
4,"Beesley, Mr. Lawrence",1,2,1,34.0,0,0,248698,13.0000,D56,S

In [75]:
def create_flag(x):
    if x< 10 :
        return "cheap"
    elif x >= 10 and x < 20 :
        return  "mid"
    else :
        return "high"

In [232]:
df['Flag_fare'] = df["Fare"].apply(create_flag)

In [76]:
df['Fare_Flag'] = df['Fare'].apply(create_flag)

In [77]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,Fare_Flag
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000,cheap
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,5702.664,high
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000,cheap
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,4248.000,high
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,644.000,cheap