In [59]:
#str methods: endswith, startswith, join, reverse, isupper, islower, isalnum, upper, len, lower,  isalpha, isspace, isdigit, strip-lr, 
#list methods: pop, remove, apend, extend, sort, reverse, join, index, min, max, len, copy
# tuple methods: count, index, min, max, len,
#dict methonds: update, fromkeys, pop, get, copy, keys, values, items, popitem, fromkeys,clear
#str value @ a idx is not modifiable
#tuple value @ a idx is not modiafiable (i.e immutable)
#set allows str and tuple to be part of it's emements (i.e immutable)
#set does not allow indexing and range accessing
#set methods: clear, copy, add, difference, intersection, union, issubset, issuperset, isdisjoint, symmetric_difference, pop, remove, update
#re methods: split, findall, compile, sub
# pd.read_csv, json, excel, html
# map(fn,ele) returns obj
# filter(fn,ele) returns obj
#lambda ele: opnD

In [20]:
pd.DataFrame([[1],[2],[3]])

   0
0  1
1  2
2  3

In [3]:
import pandas as pd
data = {'sai': [1], 'kiran':[2]}
pd.DataFrame(data)
pd.Series(data)

sai      [1]
kiran    [2]
dtype: object

In [2]:
data = {'sai':[ 1 ] ,'kiran':[ 2 ], 'patnana':[ 3 ]}
print(pd.DataFrame(data))
print(pd.Series(data))

   sai  kiran  patnana
0    1      2        3
sai        [1]
kiran      [2]
patnana    [3]
dtype: object

In [7]:
data = {'sai': 1 ,'kiran':2, 'patnana': 3}
pd.Series(data)

sai        1
kiran      2
patnana    3
dtype: int64

In [8]:
pd.Series([1,2,3],index=['sai','kiran','patnana'])

sai        1
kiran      2
patnana    3
dtype: int64

In [1]:
import pandas as pdDDDDDDD

/home/user/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [4]:
df = pd.read_csv('services.csv')

In [5]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [6]:
df.size

506

In [7]:
df.shape

(23, 22)

In [8]:
# df.to_string()

In [9]:
df.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [10]:
df.isna().sum()

id                          0
location_id                 0
program_id                 23
accepted_payments          22
alternate_name             22
application_process         0
audience                    9
description                 0
eligibility                 6
email                      22
fees                        2
funding_sources             2
interpretation_services    22
keywords                    2
languages                  22
name                        0
required_documents         22
service_areas               2
status                      0
wait_time                   4
website                    21
taxonomy_ids               22
dtype: int64

In [11]:
df.duplicated().sum()

0

In [12]:
df.describe()

             id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      object
 4   alternate_name           1 non-null      object
 5   application_process      23 non-null     object
 6   audience                 14 non-null     object
 7   description              23 non-null     object
 8   eligibility              17 non-null     object
 9   email                    1 non-null      object
 10  fees                     21 non-null     object
 11  funding_sources          21 non-null     object
 12  interpretation_services  1 non-null      object
 13  keywords                 21 non-null     object
 14  languages                1 non-null      object
 15  name                     23 non-null     object
 16  required_documents       1 non-null      object
 17  service_areas            21 non-null     object
 18  status                   23 non-null     object
 19  wait_time                19 non-null     object
 20  website                  2 non-null      object
 21  taxonomy_ids             1 non-null      object
dtypes: float64(1), int64(2), object(19)
memory usage: 4.1+ KB

In [15]:
pd.Categorical(df)

['id', 'location_id', 'program_id', 'accepted_payments', 'alternate_name', ..., 'service_areas', 'status', 'wait_time', 'website', 'taxonomy_ids']
Length: 22
Categories (22, object): ['accepted_payments', 'alternate_name', 'application_process', 'audience', ..., 'status', 'taxonomy_ids', 'wait_time', 'website']

In [16]:
pd.Categorical(df).value_counts()

accepted_payments          1
alternate_name             1
application_process        1
audience                   1
description                1
eligibility                1
email                      1
fees                       1
funding_sources            1
id                         1
interpretation_services    1
keywords                   1
languages                  1
location_id                1
name                       1
program_id                 1
required_documents         1
service_areas              1
status                     1
taxonomy_ids               1
wait_time                  1
website                    1
Name: count, dtype: int64

In [18]:
pd.Categorical(df)

['id', 'location_id', 'program_id', 'accepted_payments', 'alternate_name', ..., 'service_areas', 'status', 'wait_time', 'website', 'taxonomy_ids']
Length: 22
Categories (22, object): ['accepted_payments', 'alternate_name', 'application_process', 'audience', ..., 'status', 'taxonomy_ids', 'wait_time', 'website']

In [19]:
pd.Categorical(df['accepted_payments']).value_counts()

Cash, Check, Credit Card    1
Name: count, dtype: int64

In [20]:
df['accepted_payments'].unique()

array([nan, 'Cash, Check, Credit Card'], dtype=object)

In [21]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [22]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [23]:
df.dropna(inplace=True)

In [24]:
df.to_csv('services1.csv')

In [25]:
import warnings as warn

In [26]:
warn.filterwarnings('ignore')

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('services.csv')

In [30]:
print(df.to_string())

    id  location_id  program_id         accepted_payments         alternate_name                                                                                                                                                                                                                     application_process                                                                                                                                             audience                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description                                                                                                                                                                                                                                                                                                                                                         eligibility                  email                                                                                                                                          fees                             funding_sources                                                                                     interpretation_services                                                                                                                                                                                                                                                                                                                                                                                                 keywords languages                                  name                        required_documents                          service_areas    status                                                                                                              wait_time                 website                              taxonomy_ids
0    1            1         NaN                       NaN                    NaN                                                                                                                                                                                                              Walk in or apply by phone.                                                                                Older adults age 55 or over, ethnic minorities and low-income persons                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              A walk-in center for older adults that provides social services, wellness, recreational, educational and creative activities including arts and crafts, computer classes and gardening classes.                                                                                                                                                                                                                                                                                                  Age 55 or over for most programs, age 60 or over for lunch program                    NaN                    $2.50 suggested donation for lunch for age 60 or over, donations for other services appreciated. Cash and checks accepted.  City, County, Donations, Fees, Fundraising                                                                                                         NaN                                                                       ADULT PROTECTION AND CARE SERVICES, Meal Sites/Home-delivered Mea, COMMUNITY SERVICES, Group Support, Information and Referral, EDUCATION SERVICES, English Language, RECREATION/LEISURE SERVICES, Arts and Crafts, Sports/Games/Exercise, Brown Bag Food Programs, Congregate Meals/Nutrition Sites, Senior Centers, Older Adults       NaN       Fair Oaks Adult Activity Center                                       NaN                                  Colma    active                                                                                                               No wait.                     NaN                                       NaN
1    2            2         NaN                       NaN                    NaN                                                                                                                                                                                                      Apply by phone for an appointment.                                                                                                         Residents of San Mateo County age 55 or over                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.                                                                                                                                                                                                                                                         Age 55 or over, county resident and willing and able to work. Income requirements vary according to program                    NaN                                                                                       None. Donations requested of clients who can afford it.                      County, Federal, State                                                                                                         NaN                                                                                                                                                                                                                                                EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults       NaN      Second Career Employment Program                                       NaN                       San Mateo County    active                                                                                                                Varies.                     NaN                                       NaN
2    3            3         NaN                       NaN                    NaN                                                                                                                                                                                             Phone for information (403-4300 Ext. 4322).                                                                                          Older adults age 55 or over who can benefit from counseling                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Offers supportive counseling services to San Mateo County residents age 55 or over.                                                                                                                                                                                                                                                                                                                         Resident of San Mateo County age 55 or over                    NaN                                                                                                                                         None.                   County, Donations, Grants                                                                                                         NaN                                                                                                                                                                                                                                                                                                  Geriatric Counseling, Older Adults, Gay, Lesbian, Bisexual, Transgender Individuals, Mentoring Programs       NaN                Senior Peer Counseling                                       NaN                       San Mateo County    active                                                                                                                Varies.                     NaN                                       NaN
3    4            4         NaN                       NaN                    NaN                                                                                                                                                                                                                         Apply by phone.  Parents, children, families with problems of custody disputes, domestic violence or substance abuse, families going through a separation or divorce                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Provides supervised visitation services and a neutral site for parents to carry out supervised exchanges of children in a safe manner. Provides counseling for child abuse prevention and domestic violence.                                                                                                                                                                                                                                                                                                                                                                 NaN                    NaN                                                                    Vary according to income ($5-$90). Cash, checks and credit cards accepted.                   County, Donations, Grants                                                                                                         NaN                                                                                                                                                                           INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Growth and Adjustment, LEGAL AND CRIMINAL JUSTICE SERVICES, Mediation, Parental Visitation Monitoring, Divorce Counseling, Youth, Abuse Prevention, Child Abuse, Domestic Violence       NaN              Family Visitation Center                                       NaN                       San Mateo County    active                                                                                                               No wait.                     NaN                                       NaN
4    5            5         NaN                       NaN                    NaN                                                                                                                                                                                                                  Phone for information.               Low-income working families with children transitioning from welfare to work and poor or who do not have access to conventional credit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Provides fixed 8% short term loans to eligible applicants for the purchase of a reliable, used autmobile. Loans are up to $6,000 over 2 1/2 years (30 months). Funds must go towards the entire purchase of the automobile. Peninsula Family Service originates loans and collaborates with commercial partner banks to service the loans, helping clients build credit histories. Formerly known as Family Service Agency of San Mateo County, Ways to Work Family Loan Program.  Eligibility: Low-income family with legal custody of a minor child or an involved parent of a dependent minor child. Must reside and/or work in San Mateo County. Must be working and have verifiable income and ability to pay off loan. No bankruptcies in the past two years and unable to qualify for other funding sources. Loans approved by loan committee.                    NaN                                                                                                 $60 application fee. Cash or checks accepted.                       County, Grants, State                                                                                                         NaN                                                                                                                                                                                                                                                                                                                                                           COMMUNITY SERVICES, Speakers, Automobile Loans       NaN     Economic Self-Sufficiency Program                                       NaN                       San Mateo County    active                                                                                                                    NaN                     NaN                                       NaN
5    6            6         NaN                       NaN                    NaN                                                                                                                                                                                   Walk in or apply by phone for membership application.                                                                                                                                              Any age                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            A multipurpose center offering a wide variety of recreational, education and cultural activities.                                                                                                                                                                                                                                                                                                                                                                 NaN                    NaN                 $55 per year membership dues. Classes have fees. Discounts are available for members. Cash, checks and credit cards accepted.             Fees, Fundraising, Grants, Dues                                                                                                         NaN  ADULT PROTECTION AND CARE SERVICES, In-Home Supportive, Meal Sites/Home-delivered Meals, COMMUNITY SERVICES, Group Support, Information and Referral, EDUCATION SERVICES, Adult, HEALTH SERVICES, Education/Information, Family Support, Individual/Group Counseling, Screening/Immunization, RECREATION/LEISURE SERVICES, Sports/Games/Exercise, Community Adult Schools, Senior Centers, Older Adults       NaN  Little House Recreational Activities                                       NaN                       San Mateo County    active                                                                                                               No wait.                     NaN                                       NaN

In [31]:
df  = pd.read_csv('services.csv')

In [32]:
df.describe()

             id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [34]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [33]:
df.describe(exclude=['object'])

             id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [35]:
df.describe(include=['int'])

             id  location_id
count  23.00000    23.000000
mean   12.00000    11.956522
std     6.78233     6.711444
min     1.00000     1.000000
25%     6.50000     6.500000
50%    12.00000    12.000000
75%    17.50000    17.500000
max    23.00000    22.000000

In [36]:
df.describe(percentiles=[0.3,0.6,0.9])

             id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
30%     7.60000     7.600000         NaN
50%    12.00000    12.000000         NaN
60%    14.20000    14.200000         NaN
90%    20.80000    20.800000         NaN
max    23.00000    22.000000         NaN

In [44]:
df.sample()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [47]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [48]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [49]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [14]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [50]:
df.head(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [51]:
df.head(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [52]:
df.tail(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [53]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [54]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [55]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [56]:
df['location_id']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    22
Name: location_id, dtype: int64

In [57]:
type(df['location_id'])

pandas.core.series.Series

In [58]:
list(df['location_id'])

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 22]

In [59]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [60]:
df[['location_id']]

    location_id
0             1
1             2
2             3
3             4
4             5
5             6
6             7
7             8
8             9
9            10
10           11
11           12
12           13
13           14
14           15
15           16
16           17
17           18
18           19
19           20
20           21
21           22
22           22

In [61]:
type(df['location_id'])

pandas.core.series.Series

In [62]:
type(df[['location_id']])

pandas.core.frame.DataFrame

In [63]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [64]:
df[['keywords','status']]

                                             keywords    status
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...    active
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...    active
2   Geriatric Counseling, Older Adults, Gay, Lesbi...    active
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...    active
4      COMMUNITY SERVICES, Speakers, Automobile Loans    active
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...    active
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...    active
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...    active
8   EDUCATION SERVICES, Library, Libraries, Public...    active
9   EDUCATION SERVICES, Library, Libraries, Public...    active
10  EDUCATION SERVICES, Library, Libraries, Public...    active
11  EDUCATION SERVICES, Adult, Alternative, Litera...    active
12  EDUCATION SERVICES, Library, Libraries, Public...    active
13  COMMUNITY SERVICES, Interpretation/Translation...    active
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...    active
15  COMMODITY SERVICES, Clothing/Personal Items, C...    active
16  COMMODITY SERVICES, Clothing/Personal Items, C...    active
17  HEALTH SERVICES, Outpatient Care, Community Cl...    active
18  HEALTH SERVICES, Outpatient Care, Community Cl...    active
19                                                NaN   defunct
20                                                NaN  inactive
21                                    Salud, Medicina    active
22         Ruby on Rails/Postgres/Redis, testing, wic    active

In [65]:
df[['location_id', 'status']]

    location_id    status
0             1    active
1             2    active
2             3    active
3             4    active
4             5    active
5             6    active
6             7    active
7             8    active
8             9    active
9            10    active
10           11    active
11           12    active
12           13    active
13           14    active
14           15    active
15           16    active
16           17    active
17           18    active
18           19    active
19           20   defunct
20           21  inactive
21           22    active
22           22    active

In [66]:
df[[  'interpretation_services', 'keywords', 'languages', 'name']]

,interpretation_services,keywords,languages,name
0,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center
1,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program
2,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling
3,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center
4,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program
5,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities
6,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services
7,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County
8,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch
9,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library
10,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch
11,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read
12,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch
13,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps
14,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center
15,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps
16,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps
17,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile
18,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic
19,NaN,NaN,NaN,Service with blank fields
20,NaN,NaN,NaN,Service for Admin Test Location
21,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos
22,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name

In [67]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [68]:
df[['id', 'location_id', 'program_id', 'accepted_payments']]

    id  location_id  program_id         accepted_payments
0    1            1         NaN                       NaN
1    2            2         NaN                       NaN
2    3            3         NaN                       NaN
3    4            4         NaN                       NaN
4    5            5         NaN                       NaN
5    6            6         NaN                       NaN
6    7            7         NaN                       NaN
7    8            8         NaN                       NaN
8    9            9         NaN                       NaN
9   10           10         NaN                       NaN
10  11           11         NaN                       NaN
11  12           12         NaN                       NaN
12  13           13         NaN                       NaN
13  14           14         NaN                       NaN
14  15           15         NaN                       NaN
15  16           16         NaN                       NaN
16  17           17         NaN                       NaN
17  18           18         NaN                       NaN
18  19           19         NaN                       NaN
19  20           20         NaN                       NaN
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

In [69]:
pwd

'/home/user/Documents/DSM/PYTHON '

In [70]:
import pandas as pd

In [71]:
pip install pandas

Requirement already satisfied: pandas in /home/user/anaconda3/lib/python3.11/site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/user/.local/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/user/anaconda3/lib/python3.11/site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in /home/user/.local/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: six>=1.5 in /home/user/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [76]:
# df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

In [73]:
# df1 = pd.read_excel('LUSID Excel - Setting up your market data.xlsx')

In [74]:
df1.head(6)

NameError: name 'df1' is not defined

In [ ]:
df1.tail(3)

In [ ]:
df1.dtypes

In [ ]:
df1.columns

In [ ]:
df1['Unnamed: 0']

In [ ]:
df1[['Unnamed: 6', 'Unnamed: 7']]

In [ ]:
df2 =pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
type(df2)

In [ ]:
df2

In [ ]:
type(df2)

In [ ]:
df2.dtypes

In [ ]:
df2.head(3)

In [ ]:
df2.tail(3)

In [ ]:
df2.columns

In [ ]:
df2['Fare']

In [ ]:
type(df2['Fare'])

In [ ]:
df2[['Survived', 'Pclass', 'Name']]

In [ ]:
df2

In [77]:
df2.to_csv("titanic_data.csv",index=False)

NameError: name 'df2' is not defined

In [78]:
import lxml
import pandas as pd 
url_data = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [79]:
pip install lxml

Requirement already satisfied: lxml in /home/user/anaconda3/lib/python3.11/site-packages (4.9.1)
Note: you may need to restart the kernel to use updated packages.

In [80]:
type(url_data)

list

In [81]:
len(url_data)

2

In [82]:
df4 = url_data[0]

In [83]:
df4.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS

In [84]:
df4.tail(4)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
df4.dtypes

Rk         float64
Player      object
Age        float64
Team        object
Pos         object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Trp-Dbl    float64
Awards      object
dtype: object

In [86]:
df4.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Trp-Dbl', 'Awards'],
      dtype='object')

In [87]:
df4['Rk']

0        1.0
1        2.0
2        3.0
3        4.0
4        5.0
       ...
647    489.0
648    490.0
649    491.0
650    492.0
651      NaN
Name: Rk, Length: 652, dtype: float64

In [88]:
df4[['Pos', 'Age', 'Tm', 'G']]

KeyError: "['Tm'] not in index"

In [ ]:
df4.to_csv("players.csv" , index=False)

In [ ]:
df = pd.read_csv('services.csv')

In [ ]:
df.to_csv('Services.csv')