## Measure Of Dispersion

In [1]:
##variance
ages_lst=[23,43,23,56,74,32,68,98,45,32]

In [18]:
import numpy as numpy 
import pandas as pd
import seaborn as sns

In [21]:
np.mean(ages_lst)

49.4

In [22]:
np.median(ages_lst)

44.0

In [25]:
pd.Series(ages_lst).mode()

0    23
1    32
dtype: int64

In [26]:
import scipy.stats as stats
stats.mode(ages_lst)

ModeResult(mode=23, count=2)

In [27]:
np.std(ages_lst)

23.273160507331188

In [28]:
np.var(ages_lst)

541.64

In [4]:
mean

49.4

In [5]:
var=np.var(ages_lst)
var

541.64

In [6]:
std=np.std(ages_lst)
std

23.273160507331188

In [8]:
data=[[10,12,13],[34,23,45],[32,34,21]]
data

[[10, 12, 13], [34, 23, 45], [32, 34, 21]]

In [29]:
df = pd.DataFrame({'A': [10,12,13], 'B': [34,23,45], 'C': [32,34,21]})

In [9]:
df=pd.DataFrame(data,columns=["A","B","C"])
df

    A   B   C
0  10  12  13
1  34  23  45
2  32  34  21

In [31]:
df.head()

    A   B   C
0  10  34  32
1  12  23  34
2  13  45  21

In [33]:
df.var()

A      2.333333
B    121.000000
C     49.000000
dtype: float64

In [34]:
df.std()

A     1.527525
B    11.000000
C     7.000000
dtype: float64

In [36]:
df.mean()

A    11.666667
B    34.000000
C    29.000000
dtype: float64

In [37]:
df.mode()

    A   B   C
0  10  23  21
1  12  34  32
2  13  45  34

In [38]:
df.median()

A    12.0
B    34.0
C    32.0
dtype: float64

In [10]:
df.var()

A    177.333333
B    121.000000
C    277.333333
dtype: float64

In [40]:
df.var(axis = 0)

A      2.333333
B    121.000000
C     49.000000
dtype: float64

In [41]:
df.var(axis = 1)

0    177.333333
1    121.000000
2    277.333333
dtype: float64

In [11]:
## Row wise
df.var(axis=1)

0      2.333333
1    121.000000
2     49.000000
dtype: float64

In [12]:
## coulmnwise
df.var(axis=0)

A    177.333333
B    121.000000
C    277.333333
dtype: float64

In [43]:
len(sns.get_dataset_names())

22

In [44]:
df = sns.load_dataset('healthexp')

In [45]:
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [47]:
# df.cov()

In [55]:
df.columns

Index(['Year', 'Country', 'Spending_USD', 'Life_Expectancy'], dtype='object')

In [57]:
df[['Spending_USD','Life_Expectancy']].corr(method = 'pearson')

                 Spending_USD  Life_Expectancy
Spending_USD          1.00000          0.57943
Life_Expectancy       0.57943          1.00000

In [58]:
df[['Spending_USD','Life_Expectancy']].corr(method = 'spearman')

                 Spending_USD  Life_Expectancy
Spending_USD         1.000000         0.747407
Life_Expectancy      0.747407         1.000000

In [59]:
df[['Spending_USD','Life_Expectancy']].corr()

                 Spending_USD  Life_Expectancy
Spending_USD          1.00000          0.57943
Life_Expectancy       0.57943          1.00000